### ISSUE TITLE
unsorted output from `bcftools call -C alleles -i`

### ISSUE THREAD

**Issue by gmagoon** [samtools/bcftools#921] opened 2018-11-19 07:05 UTC
It looks like the fix for #913 has introduced another issue, where the VCF output from `bcftools call -C alleles -i` is unsorted. The #913 example case now gives the following:
```
...
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sam1
20	69066	.	C	G	60	.	DP=1;MQ0F=0;AC=0;AN=2;DP4=0,1,0,0;MQ=60	GT:PL	0/0:0,3,33
20	69094	.	G	A	.	.	.	GT	.
20	69408	.	C	T	.	.	.	GT	.
20	68799	.	T	C	.	.	.	GT	.
20	68810	.	G	A	.	.	.	GT	.
```
The expected ordering is:
```
20	68799	.	T	C	.	.	.	GT	.
20	68810	.	G	A	.	.	.	GT	.
20	69066	.	C	G	60	.	DP=1;MQ0F=0;AC=0;AN=2;DP4=0,1,0,0;MQ=60	GT:PL	0/0:0,3,33
20	69094	.	G	A	.	.	.	GT	.
20	69408	.	C	T	.	.	.	GT	.
```
I'm guessing the issue may be related to where `tgt_flush(&args,bcf_rec)` is called or how `tgt_itr_prev` is updated.

**Comment by pd3** [comment] 2018-11-19 11:04
Any chance you could send me the input files to the `bcftools call` step? I may be working with slightly different files and can't reproduce the problem.

**Comment by gmagoon** [comment] 2018-11-19 15:08
sure

[bcftools.call.bug.mpileup.zip](https://github.com/samtools/bcftools/files/2595817/bcftools.call.bug.mpileup.zip)

**Comment by gmagoon** [comment] 2018-11-19 16:09
I pasted the contents of the alleles input on #913, but I'm including the file here for the sake of completeness.
[bcftools.call.bug.als.tsv.gz](https://github.com/samtools/bcftools/files/2596102/bcftools.call.bug.als.tsv.gz)

**Comment by pd3** [comment] 2018-11-19 19:51
Thank you for the test file and the bug report. This should be now fixed by ff3137d .

**Comment by gmagoon** [comment] 2018-11-20 16:41
Thanks very much Petr.
There still seem to be a couple residual issues with `bcftools call -C alleles -i`:
-there are "duplicate" entries for some indels (though the two entries have differing allele representation, and curiously different calling results in at least some cases, too)...I'm not yet sure whether this is specific to the `-i` option or not
-for cases with multiple chromosomes/contigs, for uncovered sites preceding the first covered site on a chromosome (besides the first), bcftools waits until the very end ([this](https://github.com/samtools/bcftools/blob/develop/vcfcall.c#L445-L448) block of code) to print them out

I'll try to put together some simple examples when I get some spare time.

**Comment by gmagoon** [comment] 2018-11-21 21:58
I put together the test case shown below, which exhibits several issues with missing, duplicated, or out-of-order entries. Ideally, we'd also like to see no reads counted for the REF allele for the two deletions on chr20 (the read pair is consistent with haplotype containing the ALT allele for both deletions), but I recognize that is a tricky case (and is probably more of an issue for mpileup anyway).
Thanks for taking a look.
```
$ zcat bcftools.call.testcase.als.tsv.gz 
1	790667	C,T
1	116844268	GA,G
1	116844279	GAA,G
1	116844450	T,A
16	60288	C,A
17	355	G,A
20	68799	T,C
20	68810	G,A
20	69066	C,G
20	69094	G,A
20	69408	C,T
21	9411409	T,C
21	9411485	C,A
21	9411497	A,G
21	9412485	C,G
$ samtools view bcftools.call.testcase.bam 
rp0	163	1	116844232	60	45M3D106M	=	116844276	197	CAAGTAGCAAAACCCTGTCTCTACTAAACATACAAAGAAAAAAAAAGAAAAAAAAAAAAAAGCCGGATATGGTAGTGCATGCCTGTAATCCCAGCTACTCGGGAGGCTGAGGTGGGAGAATCACCTGAGCCAGGGAGGTCGAGGCTGCCAG	9<;>;;@?>===?@@>@=A@A>=?>>>>@?>>@?>>A?>>>>>>>+A?>>>>>>>>>>7>+:A:<5?,'?A5=>.=A<@?AA@?A8>>+AA@'BA<>+2A:55?B1A<@?A4+@54?A?>9A?@@?97AA@5A44AA49A98;.@>@?:=.	RG:Z:rg1	NM:i:6
rp0	83	1	116844276	60	4M2D147M	=	116844232	-197	AAAGAAAAAAAAAAACAAGCCGGATATGGTAGTGCATGCCTGTAATCCCAGCTACTCGGGAGGCTGAGGTGGGAGAATCACCTGAGCCAGGGAGGTCGAGTCTGCCATGAACCAAGATTAAGCCACTGCACTCCAGCCTGGGCAACCAGAG	>>>..AA@A-A@AA+,AAC6<BC+7A7CB@ABBCCABC7DBC@AA(77CADD@@DA<CCDACDDBDACCBCCDADAA:C@7DBDBD7DBCCDBCCA=DBDBDBD7CABDA;7CAACAAAABD7C?DBCC@DA7CBD7DBCCDC@?5B?A><	RG:Z:rg1	NM:i:3
rp1	99	20	68813	60	151M	=	68926	264	GGCCCTCACTTTCATGTTCTTAGATATGGTGAACAAGTCCATTGACAGTTTGTAGATTCTGTAGCACTATCATATGGAAGAGACAATATATATGTTTGGGGTAGAAGTGGAAATAAGTGGAGTGAAGACAGGATAGACAGACTAGTGACCA	?=A9:DDDDCAADDBDAADCABDCBBBDBBDCBCDBDBD9DCADCDDDAAADBBDCBADCDABCCDCDBBDCBBBDBBBDBDCCCBBAAABBBDAA@DAAAABCBACADBBBCBBBCADABC@CBBCBCCCAABACBCCCBCBBB@B??4A	RG:Z:rg1	NM:i:0
rp1	147	20	68926	60	151M	=	68813	-264	TAAGTGGAGTGAAGACAGGATAGACAGACTAGTGACCAATGGGGAGCTTCTAATTTTAGATGAATAGGAACAGTCTGTTTCCACTATTTAATAATGCTACTTTTGAAAATTGTTAACTTTTTATTAAAAAATAATACTTGCAATTGACTTA	=:==@6AAABB?AB?BA7B@@AB@@AB?>=A7@@>;B?>,,77@?A?@ABA?@A@@ABBABB?>;>5@>:BBBABAB@@A=B@DA@@@A?AA?A@BBA@B@@ABB=??@@B2@:?>?AAAAAA@@?????AA?AA>B@BBB?A@BB???==	RG:Z:rg1	NM:i:0
rp2	163	21	9412423	52	73M	=	9412423	73	ATAATTCAGTATTGAATATATAATATTATAAAATATGTAATAAAAGGATAAAAAATAAGATACAAAAAGTAAG	9;:;=<@>@<=>=@>>>=>?>=>>=>>4>=7>>>49@=>+>4>>+A4??>>+>>>>4>B7?>@@A>77A='>B	RG:Z:rg1	NM:i:0
rp2	83	21	9412423	52	73M	=	9412423	-73	ATAATTCAGTATTGAATATATAATATTATAAAATATGTAATAAAAGGATAAAAAATAAGATACAAAAAGTAAG	AAAAAACBCAAAC=ABAAAAA<AABAAAAAAAA@ABC@@;AAAAACCB@@AAAAB@AADB@@CA<@<@B>>=<	RG:Z:rg1	NM:i:0
$ bcftools mpileup -Ou -f hs37d5.fa bcftools.call.testcase.bam | bcftools call -A -C alleles -T bcftools.call.testcase.als.tsv.gz -i -m -Ov - > bcftools.call.testcase.vcf
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
$ bcftools view -H bcftools.call.testcase.vcf
1	790667	.	C	T	.	.	.	GT	.
1	116844268	.	GA	G	59	.	DP=1;MQ0F=0;AC=0;AN=2;DP4=1,0,0,0;MQ=60	GT:PL	0/0:0,3,32
1	116844279	.	GAA	G	39.5768	.	DP=1;MQ0F=0;AC=0;AN=2;DP4=0,1,0,0;MQ=60	GT:PL	0/0:0,3,13
1	116844279	.	GAAAAAAAAAAAAAAAA	GAAAAAAAAAAAAAA	24.1741	.	INDEL;IDV=1;IMF=0.5;DP=2;VDB=0.5;SGB=-0.379885;MQSB=1;MQ0F=0;AC=0;AN=2;DP4=0,1,1,0;MQ=60	GT:PL	0/0:6,0,6
20	69066	.	C	G	60	.	DP=1;MQ0F=0;AC=0;AN=2;DP4=0,1,0,0;MQ=60	GT:PL	0/0:0,3,33
20	69094	.	G	A	.	.	.	GT	.
20	69408	.	C	T	.	.	.	GT	.
21	9412485	.	C	G	79	.	DP=2;MQ0F=0;AC=0;AN=2;DP4=1,0,0,0;MQ=52	GT:PL	0/0:0,3,52
16	60288	.	C	A	.	.	.	GT	.
17	355	.	G	A	.	.	.	GT	.
20	68799	.	T	C	.	.	.	GT	.
20	68810	.	G	A	.	.	.	GT	.
21	9411409	.	T	C	.	.	.	GT	.
21	9411485	.	C	A	.	.	.	GT	.
21	9411497	.	A	G	.	.	.	GT	.
```
BAM and alleles input files, and mpileup bcf intermediate file: 
[bcftools.call.testcase.zip](https://github.com/samtools/bcftools/files/2605914/bcftools.call.testcase.zip)

**Comment by pd3** [comment] 2018-12-03 09:38
Thank you for the test cases, they were really helpful. I hope this commit b558e64 finally fixes the issue, please let me know if not!

**Closed** 2018-12-03 09:37 UTC

**Comment by gmagoon** [comment] 2018-12-04 01:47
Great, thanks very much for the update, Petr. I'll give it a shot later and will let you know if I come across any more issues related to this.
