### ISSUE TITLE
bcftools subset commands create INFO/AC, INFO/AN tags if they don't exist, but they are wrong (AC=0,AN=0 instead of AC=1,AN=1) and the header is not updated with tags definitions

### ISSUE THREAD

**Issue by rsultana** [samtools/bcftools#399] opened 2016-03-31 11:51 UTC
We have recently run into the above problem, when we split a multi-sample vcf, by keeping only one of the samples, e.g. : 

```
bcftools view -s some_sample -Ov $INFILE | bcftools convert -Oz -o $OUTFILE /dev/stdin`
```

The problem is that `$INFILE` doesn't have the `INFO/AC` and `INFO/AN` tags, but they are created anyway for each line, but as `AC=0,AN=0` although they should be in this case `AC=1,AN=1`.

Also, the tags definition is not added in the header, but the above command creates an unusable VCF file, which has the warnings for the missing headers and which breaks bcftools stats, e.g.: 

```
bcftools stats $OUTFILE
[W::vcf_parse] INFO 'AC' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'AN' is not defined in the header, assuming Type=String
[E::bcf_calc_ac] todo: 7 at 1:816258
```

This issue can be prevented by running:

```
bcftools view -s some_sample -I (or --no-update)...
```

but I think the default behaviour of bcftools subset commands should be `--no-update` if `INFO/AC` and `INFO/AN` are not present.

Regards,
Razvan

**Comment by pd3** [comment] 2016-03-31 13:46
Any chance you could provide a small example for reproducing the bug? In the meantime, there is a  workaround and a couple of things you could address:

First, the `convert` part of the command is completely unnecessary, please run instead as 

      bcftools view -s some_sample -Oz -o out.vcf.gz $INFILE

Also note that streaming plain VCF is very slow, the program first needs to convert from the internal binary representation (BCF) to VCF, then the second program converts from text to BCF only to write it as compressed text again. Whenever streaming from one bcftools command into another, use uncompressed BCF

      bcftools <command1 and args> -Ou | bcftools <command2>

Now the promised workaround: there is a plugin called `fill-tags` which can add the annotations back

      bcftools view -s sample -Ou $INFILE  | bcftools +fill-tags -Oz -o out.vcf.gz -- -t AN,AC

**Comment by rsultana** [comment] 2016-03-31 14:33
Thanks, Peter!
I'm aware of the compression/uncompression costs. The command that I posted actually had some other commands piping into one another before the final bcftools invocation. 

This was not though the point of the issue. We actually don't have AN/AC tags in the input file and we don't necessarily want them in the output file as well. 

The point was that `bcftools view -s sample` silently adds AN/AC tags with wrong values and not defined in the header. Please see what happens when you run on the attached test .vcf file this command:
```
bcftools view -s NormalID_LP2000904-DNA_B03 -Ov test.vcf
```
It adds 'AC=0;AN=0 to each line of the VCF file. 
As I said above, the fix is in fact to run the command:
```
bcftools view -s NormalID_LP2000904-DNA_B03 -I -Ov test.vcf
```

But my point was that bcftools shouldn't try by default to add invalid AN,AC tags when they don't exist in the first place.

[test.vcf.txt](https://github.com/samtools/bcftools/files/197841/test.vcf.txt)

Do you agree?

**Comment by pd3** [comment] 2016-03-31 14:40
Absolutely, this is a bug and should be fixed. Looking at your file, the error is caused by the absence of GT field. Thanks for reporting the bug!

**Comment by pd3** [comment] 2018-01-08 05:32
This is now fixed. Thank you for reporting and sorry about the delay.

**Closed** 2018-01-08 05:31 UTC
Labels: D3: Easy
