### ISSUE TITLE
bcftools filter on per-sample FORMAT fields

### ISSUE THREAD

**Issue by ksw9** [samtools/bcftools#1010] opened 2019-04-24 19:22 UTC
Hi,

I have included per-sample QUAL and FILTER information into my VCF file as you suggested in a previous post and am now attempting to filter on these FORMAT fields. I am running into some difficulty and do not seem to be setting any genotypes to no-call. I am using Version: 1.9-105-gaf6f0c9.

Thank you in advance for any suggestions. 
Best,

```
## Filter and look at an example site, in which some samples have the FORMAT field I would like to filter and set genotypes to '.' and some do not. 
bcftools filter -e 'FORMAT/FILTER == "RefCall"' --set-GTs . $vcf  | grep 150503

## Output at that site: 
NC_000962.3	150503	.	A	<*>,C	0	RefCall	ANN=C|missense_variant|MODERATE|PE_PGRS2|Rv0124|transcript|Rv0124|protein_coding|1/1|c.971A>C|p.Asn324Thr|971/1464|971/1464|324/487||	GT:GQ:MIN_DP:PL:FILTER:QUAL:DP:AD:VAF	0/0:42:54:0,42,1379,.,.,.:.:0:.:.:.	0/0:42:44:0,42,1139,.,.,.:.:0:.:.:.	0/0:50:23:0,300,2999,.,.,.:.:0:.:.:.	0/0:37:.:0,990,990,38,990,41:RefCall:0:38:33,0,5:0,0.131579	0/0:50:31:0,294,2939,.,.,.:.:0:.:.:.	0/0:45:35:0,45,929,.,.,.:.:0:.:.:.	0/0:0:34:17,0,797,.,.,.:.:0:.:.:.	0/0:21:37:0,21,929,.,.,.:.:0:.:.:.	0/0:15:55:0,15,1349,.,.,.:.:0:.:.:.	0/0:9:43:0,9,1049,.,.,.:.:0:.:.:.	0/0:45:35:0,45,929,.,.,.:.:0:.:.:.	0/0:38:.:0,990,990,38,990,44:RefCall:0:34:29,0,5:0,0.147059	0/0:1:38:5,0,905,.,.,.:.:0:.:.:.	0/0:27:39:0,27,989,.,.,.:.:0:.:.:.	0/0:50:25:0,300,2999,.,.,.:.:0:.:.:.	0/0:50:24:0,204,2039,.,.,.:.:0:.:.:.	0/0:36:.:0,990,990,37,990,40:RefCall:0:34:27,0,6:0,0.176471

## The VCF header includes this line: 
##FORMAT=<ID=FILTER,Number=1,Type=String,Description="Per-sample FILTER">
``

**Comment by pd3** [comment] 2019-04-26 14:43
I am unable to reproduce the problem. Any chance you could provide the VCF for testing? Also, even if though it will probably not help, could you test with the latest version from github?

**Comment by ksw9** [comment] 2019-04-26 23:47
Thank you! Problem resolved - I was able to work around this by naming the FORMAT/FILTER field a different name, i.e. filt. I think there may have been a name conflict issue.
Thanks again!

**Comment by pd3** [comment] 2019-04-29 11:51
I see. This is now fixed, thanks for reporting the bug.

**Closed** 2019-04-29 11:50 UTC
