### ISSUE TITLE
bcftools convert fails when converting from impute2 format to vcf

### ISSUE THREAD

**Issue by jfertaj** [samtools/bcftools#893] opened 2018-09-27 14:43 UTC
Hi,

I am trying to convert from .gen impute2 format to vcf using bcftools, the command I am using is"

      `bcftools convert -G lung_dosages/Chr${i}_imputed_filtered.gen,requite2.sample --chrom | bgzip -c > lung_dosages/Chr${i}_imputed_filtered.vcf.gz`

But I got the following error:

      `Could not parse third value of 171-th sample
       Error occurred while parsing: --- 22:16053659_A_C 16053659 A C 1.329 1.63 1.588 1.614 1.752 ... `

My samples file looks like this:

    `ID_1 ID_2 missing father mother sex plink_pheno
      0 0 0 D D D B
      468785 RQ34500-0 0 0 0 2 1 
      468787 RQ56048-6 0 0 0 1 1
      468795 RQ56085-0 0 0 0 1 1`

Any ideas?

**Comment by pd3** [comment] 2018-10-01 13:50
The error message suggests there is incorrect number of fields in the file, 3 values per sample are expected. This can be easily checked, for example with you can stream the file through `awk '{print NF}'` to verify.

**Comment by jfertaj** [comment] 2018-10-02 08:15
yo were right, I was missing a value in one of the samples, thanks!!!

**Comment by pd3** [comment] 2018-10-03 13:44
Great, glad the problem is solved, closing this issue now.

**Closed by pd3** 2018-10-03 13:44 UTC
