### ISSUE TITLE
bcftools mpileup "didn't recognize" sorted file 

### ISSUE THREAD

**Issue by fransdany** [samtools/bcftools#1639] opened 2022-01-12 03:03 UTC
Hi everyone,

I'm a novice in bioinformatics and I'm trying to make variant calling of SARS-CoV-2 by using one SRA file.

I'd like to ask about why bcftools doesn't recognized the sorted file while in fact I sorted it beforehand.

I ran this command:
$ bcftools mpileup -Ou -f reference-genome-sars-cov-2.fasta SRA_clean.bam -o SRA.pileup 

and got the following results:

[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
[E::bam_plp_push] The input is not sorted (reads out of order)

Fyi, prior to this, I did the following in order:
1. Alignment and sorting the file by Coordinate using STAR,
2. Duplication removal with Picard,
3. samtools sort for the output file resulted from the Picard's step and samtools index accordingly, and
4. primer trimming with ivar, with SRA_clean.bam as the output

The mpileup still ran though but the file size (SRA.pileup) was only 2 kb while that of SRA_clean.bam was around 40 Mb.

Am I missing something or did I do the wrong steps? 
Any inputs will be highly appreciated. 

Thank you

**Comment by jkbonfield** [comment] 2022-01-12 09:36
Normally the "input is not sorted" error is correct.

Given you also did samtools sort, that possibly implies that your step 4 broke the sort order again.  I know nothing about ivar, but I'm assuming if it's doing primer trimming that it could adjust the left end of the reads, softclipping some bases, and therefore changing the sort order again?  Try running samtools sort once more, and possibly raising this as a bug with ivar if it breaks the sort order (unless they explicitly state it does this and the documentation tells you to sort again).

**Comment by fransdany** [comment] 2022-01-13 07:28
@jkbonfield, Dear James,

Thank you very much for the reply. Yes, I think you're right that ivar might be the source of this issue. I did an experiment by rerunning the alignment using STAR yet the output BAM was without sorting (BAM Unsorted) using this command:

$ STAR --runThreadN 8 --runMode alignReads --genomeDir ~/Tes/Gen_Idx --readFilesIn ~/try/sra1_trim.fastq ~/try/sra2_trim.fastq --outSAMtype BAM Unsorted --limitBAMsortRAM 1007743684

and then did the sort again with samtools before running the ivar and when I run the ivar with the following command:
$ mv Aligned.out.bam SRA.bam
$ samtools sort SRA.bam -o SRA.sorted.bam && samtools index SRA.sorted.bam
$ ivar trim -b SARS-CoV-2.primer.bed -p SRA_clean -i SRA_sort.bam -q 15 -m 36 -s 4

I got this result:

Strand not found in primer BED file so strand will not be considered for trimming
Found 2259 primers in BED file
Amplicons detected:

Number of references in file: 1
NC_045512.2
Using Region: NC_045512.2

Found 984342 mapped reads
Found 0 unmapped reads
Sorted By Coordinate
-------
Processed 10% reads ...
Processed 20% reads ...
Processed 30% reads ... etc

The problem was 'solved' if I skipped the ivar step. The comparison between the two was:

$ bcftools mpileup -Ou -f reference-genome-sars-cov-2.fasta SRA_clean.bam -o SRA.pileup                 #ivar included
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
[E::bam_plp_push] The input is not sorted (reads out of order)

The trimming results were:
Trimmed primers from 48.65% (478907) of reads.
0.64% (6342) of reads were quality trimmed below the minimum length of 36 bp and were not written to file.
51.27% (504670) of reads that started outside of primer regions were not written to file
83.9% (825843) of reads had their insert size smaller than their read length

$ bcftools mpileup -Ou -f reference-genome-sars-cov-2.fasta SRA_sort.bam -o SRA.pileup                   #ivar skipped
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250

The warning saying "[E::bam_plp_push] The input is not sorted etc." did not appear.

Does this mean that I can exclude the ivar step or else? Thanks

**Comment by jkbonfield** [comment] 2022-01-13 09:19
> Does this mean that I can exclude the ivar step or else? Thanks

I cannot answer that question.  We provide the basic tools, rather than define pipelines and workflows.  If your experiment requires primer trimming then you'll need it or something comparable (eg samtools ampliconclip).

It's possible (but I don't know) that ivar may work on unsorted data, in which case the easy solution is to swap the order of the ivar trim and the samtools sort steps.  If it does require coordinate sorted data and you wish to continue using ivar, then you can just run the sort step a second time.

Closing the issue though as it's working as intended.

**Closed by jkbonfield** 2022-01-13 09:19 UTC
