### ISSUE TITLE
Nucleotide symbol "B" causes segfault with bcftools norm

### ISSUE THREAD

**Issue by ning-y** [samtools/bcftools#1674] opened 2022-03-09 17:15 UTC
NCBI ALFA release 2 (aka version 20201027095038) contains two insertions with `REF="B"` and therefore `ALT~"B"`:

```
NC_000003.12	16902883	rs56708014	B	BGCGC	.	.	.	AN:AC	4370:28	0:0	0:0	0:0	0:0	0:0	0:0	0:0	8:1	0:0	0:0	4378:29
NC_000003.12	16902883	rs782235056	B	BGTGC,BGTGTGTGTGTGTGCGC,BGTGTGTGTGTGTGTGTGCGC	.	.	.	AN:AC	4401:31,12,16	0:0,0,0	0:0,0,0	0:0,0,0	0:0,0,0	0:0,0,0	0:0,0,0	0:0,0,0	7:0,0,0	0:0,0,0	0:0,0,0	4408:31,12,16
```

At least one of these two records cause bcftools 1.15 using htslib 1.15 to fail with a segfault. In my situation, I used the arguments `--atomize --atom-overlaps . --multiallelics - --check-ref s --fasta-ref intermediates/alignment/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz`.

Since the VCF 4.0 specification (which is the declared VCF version in the NCBI ALFA VCF file) does not allow non-ACTGN symbols in REF and ALT, this is technically a feature request rather than a bug report. I think some nice-to-haves are:

1. Account for the "B" symbol and fix with `--check-ref s`, and/or
2. Warn or exit with a meaningful error message when the "B" symbol is encountered.

**Comment by pd3** [comment] 2022-03-29 14:41
This should be fixed, please try it out.

**Closed** 2022-03-29 14:40 UTC

**Comment by PlatonB** [comment] 2023-10-16 12:29
@pd3 The problem is relevant for BCFtools 1.18 `merge`:
```
The REF prefixes differ: BGCGC vs N (5,1)                                                                                                                                                                                                    
Failed to merge alleles at chr3:16902883 in daughter2_MP_chr3.g.vcf.gz
```

String causing the crash:
```
chr3    16902883        .       BGCGC   BGCGCGC,BGTGTGTGTGTGTGTGCGCGCGC 185.609 .       INDEL;IDV=12;IMF=0.521739;DP=23;VDB=0.00636204;SGB=-0.680642;RPBZ=-0.371391;MQBZ=0.125858;MQSBZ=-2.12132;SCBZ=-2.17842;MQ0F=0;AC=1,1;AN=2;DP4=5,2,3,9;MQ=56  GT:PL:DP        1/2:246,66,66,180,0,177:19
```

**Comment by pd3** [comment] 2023-10-21 14:52
@PlatonB Although it looks similar, this is a different problem in a different command, please open a new issue, otherwise this might get overlooked. 

If I should just comment here, the VCF specification disallows the use of non-{A,C,G,T,N} bases, so this is where the problem is coming from.
