### ISSUE TITLE
bcftools: vcfnorm.c:705: split error

### ISSUE THREAD

**Issue by mehar-GIT** [samtools/bcftools#582] opened 2017-03-30 07:47 UTC
I am trying to split multi-allelic variants in a VCF file generated by CombineVariants module in GATK. which combines the vcf files from GATK and samtools.  

$bcftools norm -m-both -o out1.vcf SNP_INDEL_raw.vcf.gz
bcftools: vcfnorm.c:705: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
Aborted

I checked the thread ( https://github.com/samtools/bcftools/issues/382 )  but did not help, which suggests something to do with AC_Het tag in the header. However, i do not have this tag in my vcf header. COuld someone help to fix this?

**Comment by mcshane** [comment] 2017-04-03 13:23
Duplicate of #581

**Closed by mcshane** 2017-04-03 13:23 UTC
