### ISSUE TITLE
bcftools merge segmentation fault

### ISSUE THREAD

**Issue by Morteza-M-Saber** [samtools/bcftools#929] opened 2018-12-02 18:52 UTC
I am trying to merge 3000 bacterial bcf files using bcftools. The vcf files has been generated using GATK and converted to bcf and indexed by bcftools. The bcftools proceeds to analyze 20% of the data but it keeps terminating premature and produces a merged bcf files only for a portion of variants ( up to 500kb from 2M bacterial genome). The code I am using is like this:

`bcftools1.7/bcftools merge  -l VarList.txt -0 --missing-to-ref --threads 16 -O b >  CombinedVCF`

The output error  is : 

`/bin/sh: line 1: 17041 Segmentation fault      (core dumped) bcftools/bcftools merge  -l VarList.txt -0 --missing-to-ref --threads 16 -O b >  CombinedVCF`

Previously I tried the same command  for 400 samples without any problem even using vcf file as input and not bcf.

Is there any solution for this or there is a limit to the total size of the files bcftools can handle.
Thanks.

**Comment by pd3** [comment] 2018-12-03 07:34
Can you try with the latest github version please?
http://samtools.github.io/bcftools/
If the problem persists, a small test case to reproduce the problem will be needed. 
Thank you

**Comment by Morteza-M-Saber** [comment] 2018-12-03 18:59
Thanks for reply but github version of bcftools also returns the same error. 
I uploaded 3000 test bcf files in figshare (https://figshare.com/articles/BCF_file_segfault/7412864). 
The error appears only for large sample sizes so I could not reduce the size any further.

Could you check the above-mentioned command on this dataset. 
Thank you.

**Comment by Morteza-M-Saber** [comment] 2018-12-04 21:55
If you need additional information to reproduce the problem, please let me know. Thanks

**Comment by pd3** [comment] 2018-12-10 13:00
Thank you for the test case and the bug report, this should be fixed now.

**Comment by Morteza-M-Saber** [comment] 2018-12-10 20:22
Thank you very much for your time.

**Comment by Morteza-M-Saber** [comment] 2018-12-10 20:58
That solved the previous error but it reemerged  in further steps downstream using bcftools. After getting the merged vcf file, I need to make some additional modification on the results by the following command:

`bcftools norm -Ou -m -any --threads 8  CombinedVCF | bcftools norm -Ou --threads 8 -f GCF_000007045.1_ASM704v1_genomic.fna | bcftools annotate -x ID -I +%CHROM:%POS:%REF:%ALT --threads 8 -o BCFToolsRes --rename-chrs ChromMap.tsv`

 bcftools produces an incomplete vcf file, a 'core.8553' file and the following error:
`Lines   total/split/realigned/skipped:	378806/0/17191/0`

Here is the reference and chromMap file needed to run the command:
https://figshare.com/articles/Segfault_sup/7445654

I would appreciate if you could take a look at it as well. Thanks.

**Comment by pd3** [comment] 2018-12-14 18:02
The problem is that in your files there are too many alternate indel alleles which makes `Number=G` fields explode, the maximum signed integer is exceeded. We should fix this in htslib, making the `bcf_format_*()` function to work with `uint32_t` or `size_t`. However, that is a bigger API-breaking change and will not happen soon. For now the only solution might be to do a multi-sample calling, that should keep the number of indels manageable.

**Comment by Morteza-M-Saber** [comment] 2018-12-14 18:31
Since our bacterial samples are highly evolving, the high number of indels are inevitable .
Using the plink, I could solve the problem for now. 
Thank you.

**Comment by pd3** [comment] 2018-12-14 18:34
A quick work around would be to drop the PL field prior to merging with `bcftools annotate -x FORMAT/PL`.

**Closed** 2018-12-20 08:55 UTC
Labels: htslib-dependent

**Comment by pd3** [comment] 2018-12-20 08:59
I just improved the original fix: the tags with more values than we can handle are now skipped with a warning. This should produce normal VCF files with PL field occasionally missing, should the number of values exceed the maximum signed integer, as was the case with your VCF.
