### ISSUE TITLE
bcftools consensus not working when using -H flag

### ISSUE THREAD

**Issue by everestial** [samtools/bcftools#795] opened 2018-05-17 19:47 UTC
I am trying to get both the left and right reference genome to create a personal genome using a sample name in phased VCF file. 

This works: 
    
    bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s ms01e -H 1 > ms01e-left.fa

This doesn't work though: 
when I am trying to make the new Ref Sequence by imputing genotype from the right haplotype of the "GT" field.

    bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s ms01e -H 2 > ms01e-right.fa
    Broken VCF, too few alts at 1:141

**What is the issue ?**

This is cross post from biostars: https://www.biostars.org/p/315458/#315569 and includes the discussion.
I am raising the issue here hoping it might find a quicker fix.

Thanks,

**Comment by pd3** [comment] 2018-05-18 08:07
Hmm, this should work unless I misunderstood what the issue is about. Any chance you could provide a small reproducible test case to debug the problem?

**Comment by everestial** [comment] 2018-05-18 13:12
@pd3 @finswimmer

I have attached the files:

    # imputation using the right genotype doesn't work
    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 2  > BcfOut/MA625-right.fa
Broken VCF, too few alts at 1:1092

    # but "." isn't a problem if I am requesting  a left haplotype
    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 1  > BcfOut/MA625-left.fa

    # I also tried to use "-i " flag
    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 2 -i 'GT="."' > BcfOut/MA625-right.fa
    Broken VCF, too few alts at 1:1092

    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 2 -i 'GT="\."' > BcfOut/MA625-right.fa
    # this goes through but doesn't produce the imputed alleles

   $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 2 -i 'GT!~"\."' > BcfOut/MA625-right.fa
    Broken VCF, too few alts at 1:1092
    
    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 2 -i 'GT~"\."' > BcfOut/MA625-right.fa
    Broken VCF, too few alts at 1:1092

typically speaking existence of `GT as . ` must not be a problem as the program should assume that the GT is missing. 
<br> 
**As per documentation:** 

     missing genotypes can be matched regardless of phase and ploidy (".|.", "./.", ".") using these expressions
    GT~"\.", GT!~"\."

**Here are the files:**

[lyrata_chr01-short.fasta.gz](https://github.com/samtools/bcftools/files/2016966/lyrata_chr01-short.fasta.gz)
[phasedVCF-short.vcf.gz](https://github.com/samtools/bcftools/files/2016967/phasedVCF-short.vcf.gz)

**Comment by pd3** [comment] 2018-05-18 13:41
@everestial From a cursory glance, I don't think this is a problem of handling missing genotypes. It looks more like a bug in htslib parsing of the VCF. Will need more time to verify and fix. In the meantime, thanks for reporting.

**Comment by everestial** [comment] 2018-05-18 14:08
@pd3 @finswimmer 
I just reinstalled the htslib and bcftools and samtools and problem still persists. So, yeah it should be a bug.

**Additional issues:\**
**Direct piping didn't work:**

    bcftools view -s MA625 phasedVCF-short.vcf.gz -U | bcftools consensus -f lyrata_chr01-short.fasta -s MA625 -H 2  > BcfOut/MA625-right.fa

**This didn't work either:**
 
    bcftools view -s MA625 phasedVCF-short.vcf.gz > phasedVCF-short-MA625.vcf.gz
    bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short-MA625.vcf.gz -s MA625 -H 2  > BcfOut/MA625-right.fa
    Failed to open phasedVCF-short-MA625.vcf.gz: not compressed with bgzip

<br>

**What ended up working was this code (way longer and time consuming):**

    $ bcftools view -s MA625 phasedVCF-short.vcf.gz -U > phasedVCF-short-MA625.vcf.gz
    $ bgzip phasedVCF-short-MA625.vcf
    $ tabix -f phasedVCF-short-MA625.vcf.gz
    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short-MA625.vcf.gz -s MA625 -H 2  > BcfOut/MA625-right.fa

which will end up taking so much more time in a larger data set with numerous samples.
<br>

Making this (below) code work would be a neat and fastest way:

    $ bcftools consensus -f lyrata_chr01-short.fasta phasedVCF-short.vcf.gz -s MA625 -H 2 -i 'GT="."' > BcfOut/MA625-right.fa

**Comment by pd3** [comment] 2018-05-18 17:50
Thank you for the bug report, this should be now fixed by https://github.com/samtools/bcftools/commit/bbf15837d164fa33718509e8d81e2d833e3513e4. Please reopen if not.

**Closed by pd3** 2018-05-18 17:50 UTC
