### ISSUE TITLE
bcftools gtcheck issue with discordance output value

### ISSUE THREAD

**Issue by ashleymulford** [samtools/bcftools#1556] opened 2021-08-16 16:22 UTC
I am trying to check the genotype concordance/sample identity with bcftools gtcheck for a set of vcf files I have. I have vcfs that have been generated from two different sequencing methods for multiple samples, so for each sample there are two vcfs (one from each method) that contain some overlapping positions and I am trying to determine the concordance between the two files for each sample. I successfully ran bcftools gtcheck with the following command format:

bcftools gtcheck -g sample_method1.vcf.gz sample_method2.vcf.gz > sample_gtcheck_results.txt

Here is an example of the output:
INFO	Time required to process one record .. 0.000071 seconds
INFO	sites-compared	30995
INFO	sites-skipped-no-match	3551171
INFO	sites-skipped-multiallelic	0
INFO	sites-skipped-monoallelic	0
INFO	sites-skipped-no-data	0
INFO	sites-skipped-GT-not-diploid	0
INFO	sites-skipped-PL-not-diploid	0
#DC, discordance:
     query sample
     genotyped sample
     discordance (number of mismatches; smaller is better)
     negative log of HWE probability at matching sites (rare genotypes matches are more informative, bigger is better)
     number of sites compared (bigger is better)
#DC	[2]Query Sample	[3]Genotyped Sample	[4]Discordance	[5]-log P(HWE)	[6]Number of sites compared
DC	sample	sample	7.711017e+03		1.666131e+05		30906

Some context: one method was imputed while another was not, hence the large number of sites skipped. The sites that do overlap and were compared are distributed fairly evenly across chromosomes. The file specified as the reference with -g is the non-imputed file with approximately 800,000 total sites.

I am confused by the output for [4]Discordance. The explanation provided in the output says it is the number of mismatches, however this value is in scientific notation and is equivalent to 7711.017, which is not a whole number, and I am confused how there could be a fractional mismatch. Additionally, 7711 mismatches out of 30906 sites compared is a larger proportion than I would expect for data generated from the same sample. I investigated this further by running bcftools gtcheck with a smaller region and then I ran a script of my own that parses the vcf files and compared the genotypes in the same region. When doing this I got the same number of sites compared, however the value for [4]Discordance was 10 times higher than the number of mismatches my script calculated. For example, if my script determined that 2 mismatches occurred, gtcheck would return that 2.0e+01 (=20) mismatches occurred. This pattern of the value being off by 10 times occurred consistently across all samples and regions I checked. Additionally, I do believe the value my script is obtaining is correct, as I attempted running gtcheck with samples I knew to not match and the value for [4]Discordance was greater than the value for [6]Number of sites compared, though not by larger than 10 times.

Could someone explain how discordance is being calculated, why it would be fractional/in scientific notation, and if anyone else has experienced the value being off by a factor of 10?

Thanks!

**Comment by pd3** [comment] 2021-08-17 11:32
This looks like a duplicate of https://github.com/samtools/bcftools/issues/1538.

Use `-e 0` to get the number of mismatches instead of the default score.

**Closed by pd3** 2021-08-17 11:32 UTC
