### ISSUE TITLE
bcftools merge do not output all variants and compression is corrupted

### ISSUE THREAD

**Issue by mariabernard** [samtools/bcftools#1097] opened 2019-10-30 09:14 UTC
Dear all

I am currently merging 2 vcf.gz files:
- set1 : 61 samples, 31,441,105 variants
- set2 : 24 samples, 17 889 078 variants

My first test is 
```
bcftools merge -o merge.vcf.gz -O z --threads 8 set1.vcf.gz set2.vcf.gz
```
no error returned, but when I simply count the number of variants
```
zcat merge.vcf.gz | grep -vc "#"
gzip: Results/USDA.vcf.gz: unexpected end of file
35 696 350
```

So I tried without the compression
```
bcftools merge -o merge.vcf --threads 8 set1.vcf.gz set2.vcf.gz
grep -vc "#" merge.vcf
35 724 790
```
and to be shure I compare with vcf-merge

```
vcf-merge set1.vcf.gz set2.vcf.gz > vcf-merge.vcf
grep -vc "#" vcf-merge.vcf
35 732 342
```

The difference between vcf-merge and bcftools merge is due to 7552 variants that are on reference sequence that are present in only one of the 2 sets. 

I checked the man page, but I am not shure that I needed to add some options to effectively obtain all variants even if the reference is completly absent of one of the set. Am I missing something ?

Regards

Maria

**Comment by pd3** [comment] 2019-10-30 13:34
The usage looks correct. In order to debug this, can you please check a few things:

- are the input VCF valid? This can be checked with vcf-validator which seems to be installed on your system, given you used vcf-merge.

- what version of bcftools are you running, can you try with the latest development version? Installation instructions are here http://samtools.github.io/bcftools/howtos/install.html.

- if the above does not help, can you provide a reproducible test case?

**Comment by pd3** [comment] 2019-10-31 07:35
Glad to hear the latest version solves the problem. Closing the issue now.

**Closed by pd3** 2019-10-31 07:35 UTC
