### ISSUE TITLE
Long running time bcftools roh on RAD-seq data: is it 'expected'?

### ISSUE THREAD

**Issue by xgabrix** [samtools/bcftools#1687] opened 2022-03-25 19:14 UTC
Hi,

I am testing bcftools roh on a simulated RAD-seq dataset to see the extent on which bcftools roh can estimate the correct ROH distribution.

I have run the software using the following command:
error_rate=30
recomb_rate=7e-8
input=chrom2.vcf
output=output_ROH_RAD_data.txt

bcftools roh --GTs-only ${error_rate} --estimate-AF - --rec-rate $recomb_rate $input --output $output

The analysis did not conclude after more than 17 hours analysis on 1 node and 20G of RAM memory. I had to stop the running process since I could not figure out if this long running time is expected (due to the sparse distribution of variant sites in RAD-seq datasets or to the low number of SNPs).

What to do you think? What could I do to figure out what is happening?

Here you can find the dataset I have used (downloadable from WeTransfer): https://we.tl/t-92hRTg3Trg
If you do not want to download it, I can post the entire VCF file here.

Thank you in advance.

**Comment by pd3** [comment] 2022-03-29 10:34
Such a long run for such a small VCF, that indeed does not sound right. What version of bcftools have you used?

**Comment by xgabrix** [comment] 2022-03-29 16:30
I have used bcftools-1.14. I have also noticed that if I replace --estimate-AF - with --Af-dflt 0.4 the analysis run smoothly. My guess is that for some reason the program has some difficulties on reaching convergence for estimate AF, but just a guess. I was planning to test difference --AF flags, as you suggest in the tutorial.

Let me know what do you think and thanks!

**Comment by pd3** [comment] 2022-03-30 07:35
Thank you for the bug report and the test case, the problem is now fixed.

**Closed** 2022-03-30 07:35 UTC
