### ISSUE TITLE
+tag2tag --gp-to-gl doesn't produce FORMAT/GL field

### ISSUE THREAD

**Issue by sahwa** [samtools/bcftools#1398] opened 2021-02-04 11:50 UTC
test.vcf:

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##source=atlas
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AB,Number=1,Type=Float,Description="Allelic imbalance">
##FORMAT=<ID=AI,Number=1,Type=Float,Description="Binomial probability of allelic imbalance if Hz site">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
##FORMAT=<ID=GP,Number=G,Type=Integer,Description="Genotype posterior probabilities (phred-scaled)">
##contig=<ID=1>
##contig=<ID=2>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##contig=<ID=X>
##contig=<ID=Y>
##bcftools_viewVersion=1.10+htslib-1.10
##bcftools_viewCommand=view -r 21 -Ob allBavarianAncients.bgz.vcf.gz; Date=Wed Feb  3 18:05:29 2021
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##bcftools_viewVersion=1.11-60-g09dca3e+htslib-1.11-82-g2d1e954
##bcftools_viewCommand=view -r 21:14601415,21:14977445 -s Alh10 allBavarianAncients.chr21.newnames.bgz.vcf.gz; Date=Thu Feb  4 11:43:12 2021
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Alh10
21	14601415	.	G	A	.	.	DP=118;AC=0;AN=2	GT:AD:AB:AI:DP:GQ:GP	0/0:6,0:1:0.015625:6:46:0,51,221
21	14977445	.	C	T	.	.	DP=10;AC=0;AN=2	GT:AD:AB:AI:DP:GQ:GP	0/0:1,0:1:0.5:1:30:0,36,42
```
running:

`bcftools +tag2tag test.vcf -- --gp-to-gl`

produces:

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##source=atlas
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AB,Number=1,Type=Float,Description="Allelic imbalance">
##FORMAT=<ID=AI,Number=1,Type=Float,Description="Binomial probability of allelic imbalance if Hz site">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
##FORMAT=<ID=GP,Number=G,Type=Integer,Description="Genotype posterior probabilities (phred-scaled)">
##contig=<ID=1>
##contig=<ID=2>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##contig=<ID=X>
##contig=<ID=Y>
##bcftools_viewVersion=1.10+htslib-1.10
##bcftools_viewCommand=view -r 21 -Ob allBavarianAncients.bgz.vcf.gz; Date=Wed Feb  3 18:05:29 2021
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##bcftools_viewVersion=1.11-60-g09dca3e+htslib-1.11-82-g2d1e954
##bcftools_viewCommand=view -r 21:14601415,21:14977445 -s Alh10 allBavarianAncients.chr21.newnames.bgz.vcf.gz; Date=Thu Feb  4 11:43:12 2021
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihoods">
##bcftools_pluginVersion=1.11-60-g09dca3e+htslib-1.11-82-g2d1e954
##bcftools_pluginCommand=plugin tag2tag -- test.vcf --gp-to-gl; Date=Thu Feb  4 11:48:13 2021
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Alh10
21	14601415	.	G	A	.	.	DP=118;AC=0;AN=2	GT:AD:AB:AI:DP:GQ:GP	0/0:6,0:1:0.015625:6:46:0,51,221
21	14977445	.	C	T	.	.	DP=10;AC=0;AN=2	GT:AD:AB:AI:DP:GQ:GP	0/0:1,0:1:0.5:1:30:0,36,42
```
i.e. the GL format tag is present in the header, but it's not added to the format fields in the main body of the vcf. Is this something I am doing wrong or a bug?

```
bcftools  1.11-60-g09dca3e using htslib 1.11-82-g2d1e954
plugin at 1.11-60-g09dca3e using htslib 1.11-82-g2d1e954
```

**Comment by pd3** [comment] 2021-02-05 08:38
Thank you for raising the issue. This is caused by GP being incorrectly defined as `Type=Integer` rather than `Type=Float` in the header. Ideally this should be fixed on producer's end. As a quick workaround you can use `bcftools reheader` to fix the header and then it should work.

**Closed** 2021-02-10 09:05 UTC

**Comment by pd3** [comment] 2021-02-10 09:15
I just pushed a small improvement, the program will exit with an error if the type does not match the expectation and will suggest the use of `reheader`.
