### ISSUE TITLE
bcftools view -R can duplicate records

### ISSUE THREAD

**Issue by bioinformed** [samtools/bcftools#562] opened 2017-03-01 16:21 UTC
Version: 1.3.1-216-gcafabaa (using htslib 1.3.2-205-gf476b53)

Input VCF, BED; Output VCF: [dup_test.zip](https://github.com/samtools/bcftools/files/811301/dup_test.zip)

```shell
$> cat dup_test.bed
chr1	156134804	156134974
chr1	156135186	156135311

$> bcftools view -H dup_test.vcf.gz
chr1	156134692	.	C	<NON_REF>	.	PASS	END=156135413	GT:DP:GQ:MIN_DP:GL	0/0:126:99:39:-0,-10.5,-148.1

$> bcftools view -R dup_test.bed -Ov dup_test.vcf.gz > dup_out.vcf

$> bcftools view -H dup_out.vcf
chr1	156134692	.	C	<NON_REF>	.	PASS	END=156135413	GT:DP:GQ:MIN_DP:GL	0/0:126:99:39:-0,-10.5,-148.1
chr1	156134692	.	C	<NON_REF>	.	PASS	END=156135413	GT:DP:GQ:MIN_DP:GL	0/0:126:99:39:-0,-10.5,-148.1
```

In addition, using `bcftools view -T` rather than `-R` yields no records.  I can file this as a separate issue, if this is also erroneous behavior.

**Comment by pd3** [comment] 2017-03-02 19:42
It is not a bug, but a rather non-intuitive behavior.
The `-R` option uses index to retrieve all records that overlap the interval. Your VCF record is long, so both regions fall into it. On the other hand the `-T` option streams the whole VCF and skips records that do not match the first coordinate. This is described in the manual page and is one of the things that I am considering to change in future releases.

**Comment by bioinformed** [comment] 2017-03-02 20:27
@pd3: Ugh.  No worries -- we can work around these issues.  However, as a user, I'm not sure either behavior is ideal.  Personally, I'd prefer it if `-R` and `-T` both produced identical subsets of the original VCF (with no duplicates).

**Comment by dancooke** [comment] 2017-05-24 08:20
Any progress on this? I'm also running into trouble with this behaviour and agree with @bioinformed that both options should produce identical subsets.

**Comment by finswimmer** [comment] 2019-10-17 04:53
Hello,

while I understand the reason for the duplicate records when using `-R`, I'm absolutely sure, that this is an unexpected behavior to most (if not all) users.

Filtering a vcf file should not produce more records.

Any plans for fixing it?

Thanks a lot!

fin swimmer

**Comment by pd3** [comment] 2019-10-17 21:44
I agree it would be good to address this finally but there is no timeline or plan. The change will have to be at the htslib level, therefore it would need to be thought through carefully. Some thoughts on desired features and the strategy:

- The `-T` option operates on the starting coordinate while `-R` pulls in overlapping records.  The new version should be able to support both modes. Either a new option would have to be added to every bcftools command or the behavior might be requested by adding a special prefix, e.g. `-R regions.bed` vs `-R +regions.bed`, where the first considers only the starting coordinate whereas the latter pulls in overlaps. Although a bit obscure and has a risk of file name conflicts (albeit small), it adds functionality without having to make any changes in programs, similarly to https://github.com/samtools/htslib/pull/861.

- The current handling of regions is quite flexible, supports both indexed and unindexed region files and is able to keep the memory usage low even for big files. Merely switching to [regidx](https://github.com/samtools/bcftools/blob/develop/regidx.h) may not be desired because it would blow up memory for large region files, as happened recently here https://github.com/samtools/bcftools/issues/1047#issuecomment-525554270.

- With the `-R`option, the order of data records on output is currently defined by the order of regions in the `-R` file.  In order to unify the behavior of `-R` and `-T`, this will have to change and the order of records on output will have to follow the order in the data file instead. It seems unavoidable that the `-R` file must be first parsed, sorted to reflect the ordering of the data file, then regions merged.

**Comment by valeriuo** [comment] 2019-10-18 09:41
The htslib iterator, which is also being used by bcftools, has multi-region support and could be used in a similar way in which `samtools view -M` operates. It constructs a single iterator with multiple unique file location, that is persistent between file operations (seek and read). 
In this manner, a file location will not be visited twice, as it happens now with `-R` option, when different region specifiers generate identical file iterators.

**Comment by pd3** [comment] 2019-11-07 15:46
Hopefully this should be fixed by https://github.com/samtools/htslib/commit/db90fb58b06d6f3b27b5b873588da7c77844da22. Can you please try it out?

**Comment by finswimmer** [comment] 2019-11-07 16:24
Made just a short test, but that looks good to me :+1: 

Are there any release plans for samtools/bcftools/htslib 1.10?

Thanks a lot!

**Comment by pd3** [comment] 2019-11-08 10:18
A new release is imminent. Thank you for testing. I will mark this issue as resolved now.

**Closed by pd3** 2019-11-08 10:18 UTC
Labels: P2: Desirable
