### ISSUE TITLE
bcftools mpileup: extremely slow when -C, -R and -T options apply

### ISSUE THREAD

**Issue by rcheng** [samtools/bcftools#1560] opened 2021-08-22 18:04 UTC
It is pretty fast when options -C, -R and -T do not apply but very slow otherwise. Options -C, -R and -T were wanted because the focus was on known biallelic SNPs, and of course the number of such sites is much smaller. Not sure what slowed down the processing in such a case where the REF/ALT alleles are given and the number of sites is much smaller. It should take much less time if numeric convergence is not relevant.

**Are there any strategies to resolve the speed problem**? Would it help to process 1) samples one by one or 2) genome piece by piece without loss of precision? (Or, is there any room to improve speed by refining the algorithm or programming?)

Thanks a lot!!!

**Comment by pd3** [comment] 2021-08-23 14:19
What version of bcftools and htslib are you using?

This should not be the case. The `-R` option allows to jump to a region of interest using an index. If there are only a few sites and the alignment file is big, this always helps significantly. On the other hand, `-T` merely skips positions/regions not listed in the region file. I don't know about `-C`.

It is not clear from your description if it's the combination of all three that slows down the processing for you or if you observe the slowdown when applying individually. Also not sure what do you mean by giving REF/ALT alleles? Possibly you mean `bcftools call -C` rather than `bcftools mpileup -C`?

**Comment by rcheng** [comment] 2021-08-23 17:56
Thank you for response! 

I used bcftools 1.12 and htslib 1.12. Is it my mistake to use -C option in mpileup that caused the problem? The -C option in mpileup has a different meaning. I only wanted to get genotypes at a given list of SNPs (with known reference and alternative alleles) and I used the -T option in call. Do I need the -T option (in addition to the -R option) in mpileup?

I'll remove -C from mpileup and try again.

Thank you again!

**Comment by pd3** [comment] 2021-08-24 08:45
The `mpileup -T` option is not needed.

**Comment by rcheng** [comment] 2021-09-06 02:48
I've removed -C from mpileup. This run hasn't finished yet. It seems slightly faster but is still VERY slow.

Without -R in mpileup and -T in call, the program was pretty fast and generated data that is much larger in size and has many more sites. Not sure why it gets slow when restricted to a list biallelic sites.

**Comment by pd3** [comment] 2021-09-06 08:05
That's odd. Any chance you could create a smallish test case from your data, show the full commands and timings to reproduce the problem on our side?

**Comment by rcheng** [comment] 2021-09-06 18:02
I've been looking at chromosome 1. There are 1,912 samples. The bam file size varies from ~100Mb to 2.5Gb. There are a total of 1,072,434 biallelic sites. About **71 hours** have passed by now. Only **25,8428 sites** have been processed so far. The code is as follows.

   of=Tmp/chr$(printf "%02d" $chr)_smtl_refAll.vcf.gz
   bcftools mpileup --no-version -a FORMAT/DP -q 13 -Q 13 \
      --threads $ncpu \
      -R ${Rf}.gz \
      -f $ref \
      -O v \
      $fls | \
   bcftools call --no-version -m -A \
      --threads $ncpu \
      -C alleles \
      -T ${Tf}.gz \
      -O z \
      -o $of

where chr=1, Rf=Tmp/chr$(printf "%02d" $chr).rsv, Tf=Tmp/chr$(printf "%02d" $chr).tsv, ref is the reference genome, and ncpu=24. (**A total of 24 cores are used to process the data**.)

The first few lines of Tmp/chr01.rsv.gz:
chr1    4441
chr1    4785
chr1    34506
chr1    35129
chr1    35130
chr1    35132

The firs few lines of Tmp/chr01.tsv.gz:
chr1    4441    C,T
chr1    4785    A,G
chr1    34506   A,C
chr1    35129   T,C
chr1    35130   C,T
chr1    35132   T,C
chr1    35361   T,C

**Comment by pd3** [comment] 2021-09-07 14:49
You should use `-Ou` when streaming from one bcftools command into another.

Can you take the first 1k sites of raw mpileup output (`bcftools mpileup ... -Ob -o raw.bcf`) and show the timings when you run these two commands:
```
/usr/bin/time bcftools call -mA -Ou -o /dev/null
/usr/bin/time bcftools call -mA -Ou -o /dev/null -C alleles -T targets.gz 
```
There is some computational overhead with `-C alleles`, but it should not be prohibitive.

**Comment by rcheng** [comment] 2021-09-07 23:47
The first **10,000 sites** were used for testing. **Timing information is as follows**. (The call command finished very quickly, just in seconds!)
Tue Sep  7 **10:12:01** PDT 2021
[mpileup] 1912 samples in 1912 input files
[mpileup] maximum number of reads per input file set to -d 250
Tue Sep  7 **12:45:20** PDT 2021
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
Tue Sep  7 **12:45:25** PDT 2021
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
Tue Sep  7 **12:45:29** PDT 2021

**The code is as follows**.
   echo "$(date)"
   of=Tmp/chr$(printf "%02d" $chr)_smtl_refAll.bcf
   bcftools mpileup --no-version -a FORMAT/DP -q 13 -Q 13 \
      --threads $ncpu \\
      -R ${Rf}.gz \\
      -f $ref \\
      -O b \\
      -o $of \\
      $fls
   echo "$(date)"
   fl=$of
   of=Tmp/chr$(printf "%02d" $chr)_smtl_refAll_1.vcf.gz
   bcftools call --no-version -m -A \\
      --threads $ncpu \\
      -O z \\
      -o $of \\
      $fl
   echo "$(date)"
   of=Tmp/chr$(printf "%02d" $chr)_smtl_refAll_2.vcf.gz
   bcftools call --no-version -m -A \\
      --threads $ncpu \\
      -C alleles \\
      -T ${Tf}.gz \\
      -O z \\
      -o $of \\
      $fl
   echo "$(date)"

The **number of cores was 16**. If time is linear in the number of cores and the number of sites, then it would take **about 7.6 days** to finish the chromosome using 24 cores; however, it actually took 24 cores nearly 2 weeks. Does this mean that splitting the chromosome into pieces can spare time?

By the way, the mpileup produced 10,071 sites; however, call with -C and -T options generated 9,711 sites.

**Comment by pd3** [comment] 2021-09-08 08:44
You ran something else from what I asked.

**Comment by rcheng** [comment] 2021-09-08 15:17
Well, basically the call did take little time (so it is mpileup that takes time). Using the 10,000 sites, I ran your commands as follows.
[ric025@tscc-10-7 hsRats]$ Tf=Tmp/chr01.tsv.gz
[ric025@tscc-10-7 hsRats]$ fl=Tmp/chr01_smtl_refAll.bcf
[ric025@tscc-10-7 hsRats]$ /usr/bin/time bcftools call -mA -O z -o /dev/null $fl
ll -mA -C alleles -T ${Tf} -O z -o /dev/null $fl
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
6.16user 0.09system 0:06.40elapsed 97%CPU (0avgtext+0avgdata 6596maxresident)k
34240inputs+0outputs (25major+24535minor)pagefaults 0swaps
[ric025@tscc-10-7 hsRats]$ /usr/bin/time bcftools call -mA -C alleles -T ${Tf} -O z -o /dev/null $fl
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
4.76user 0.02system 0:04.80elapsed 99%CPU (0avgtext+0avgdata 8060maxresident)k
72inputs+0outputs (0major+9848minor)pagefaults 0swaps

**Comment by pd3** [comment] 2021-09-08 15:49
This suggests that there is no significant difference between running `bcftools call` with and without `-C`,`-T`.  And since `mpileup` is run the same way in both runs, I can think of two possible causes only: either there is some slowdown on the computing cluster unrelated to bcftools, or there is a specific site where the program gets stuck. I don't think the latter is very likely, but you can test that by adding a debug printout to the code
```
fprintf(stderr,"%s:%d\n",bcf_seqname(args.aux.hdr,bcf_rec),(int)bcf_rec->pos+1);
```
just above this line https://github.com/samtools/bcftools/blob/develop/vcfcall.c#L1107

If the program stops printing the positions on stderr, that would indicate there is a problem at the site last printed.

**Comment by rcheng** [comment] 2021-09-08 20:32
Does mpileup involve optimization that needs a number of iterations for convergence? Slow convergence is a common problem in numeric optimization. Slower speed for a given list of sites didn't seem to be caused by the cluster. I ran multiple chromosomes (or the same chromosome for multiple times) using different nodes and had basically the same problem.

If the program can get stuck at a small number of sites, would it be better to split a chromosome into a number of pieces and process the pieces in parallel (instead of using multiple threads, supposing multiple threading doesn't do a similar thing)? This assumes splitting a chromosome would not impact the result.

**Comment by pd3** [comment] 2021-09-09 06:25
No, there are no iterations, if it gets stuck anywhere, that would be a bug and should be fixed. Threading is used only for compression/decompression, this is mentioned in the manual page.

**Comment by rcheng** [comment] 2021-09-10 06:20
I see. So it should be helpful to run the program in parallel if splitting the chromosome doesn't have a negative impact on accuracy.

For your information, the program didn't get stuck forever but seemed to be slower (i.e., it processed less sites in a longer time)

**Closed** 2021-09-10 06:20 UTC
Labels: requires-test-case
