### ISSUE TITLE
Expression problems in bcftools view

### ISSUE THREAD

**Issue by pishotta** [samtools/bcftools#201] opened 2015-02-02 23:56 UTC
<pre>Commands like:
"bcftools view -i 'ref="A"' p3.vcf.gz" work fine, yielding lines like

>> chr1    883619  .       A       .       999     .       DP=44;MQSB=1;MQ0F=0...
>> chr1    883622  .       A       .       999     .       DP=45;MQSB=1;MQ0F=0...
>> chr1    883625  .       A       G       141     .       DP=45;VDB=6.66888e-18...
>> chr1    883627  .       A       .       999     .       DP=46;MQSB=1;MQ0F=0;AN=2;DP4=1,45,0,0...
>> chr1    883629  .       A       .       999     .       DP=46;MQSB=1;MQ0F=0;AN=2;DP4=1,44,0,0...

"bcftools view -i 'alt="G"' p3.vcf.gz" yields every line with either a "G" or a "." in 
the ALT column.  Not the behavior I expect/want.

>> chr1    908306  .       G       .       999     .      DP=143;MQSB=0.20004...
>> chr1    908309  .       G       .       27.283  .      DP=139;VDB=0.478589;SGB=-0.651104...
>> chr1    908310  .       C       G       7.91518 .      DP=112...
>> chr1    908311  .       C       .       999     .      DP=139;MQSB=0.774446...
>> chr1    908314  .       C       .       999     .      DP=137;MQSB=0.701554...

"bcftools view -i 'alt="G" && ref="A"' p3.vcf.gz" prints the header then dumps core.  Ouch!
"bcftools view -v snps -i 'alt="G" && ref="A"' p3.vcf.gz" seem to work OK.
The "." in the ALT column would seem to be the problem.

Have tried many syntactic variations to no avail.  Using Version: 1.2-1-gf0a7dcd, and 
htslib 1.2-1-gb0742b0.  Peculiar.

-- Fred P.
</pre>

**Comment by pd3** [comment] 2015-02-03 08:16
Hi Fred, can you run `make clean` in both htslib and bcftools and recompile? If the problem persist, can you please send me a small test case? I am not able to reproduce the problem with my data.

**Comment by mp15** [comment] 2015-02-03 17:53
Oops, I didn't realise the attribute's message syntax was a late addition. I'll add a pull to fix it for legacy compilers.

Sent from my iPhone

> On 3 Feb 2015, at 16:46, John Marshall <notifications@github.com> wrote:
> 
> Note btw that that's the current develop rather than "the latest release".
> 
> If you checkout the latest htslib release (cd htslib; git checkout 1.2.1) you'll avoid this problem too.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by pishotta** [comment] 2015-02-03 17:55
OK, compile problems resolved, thanks, but with the attached test file:

>--> bcftools view -i 'ref="A"' test.vcf.gz <--< works OK, but
>--> bcftools view -i 'alt="A"' test.vcf.gz <--< dumps core.

It's a RHEL6 linux system.
[root@ubccan-hpmysql /vcf_repo]# uname -a
Linux ubccan-hpmysql 2.6.32-504.8.1.el6.x86_64 #1 SMP Fri Dec 19 12:09:25 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pishotta** [comment] 2015-02-04 16:48
<pre>Update...
I recompiled and re-ran the above commands on a different system under RHEL7...

> [root@ubccan-s-tardis bcftools]# uname -a
> Linux ubccan-s-tardis.can.ubc.ca 3.10.0-123.13.2.el7.x86_64 #1 SMP Thu Dec 18 14:09:13 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

...with the same results.  Core dump trying to check the ALT field.  I then replaced all the
"." characters in the ALT column of the vcf file with an "A", and the command completed
successfully.  Continuing to experiment, I note that the problem does not occur if there
is a "." in the REF column, only when there is one in the ALT column.  I grant that most
vcf files would not contain a "." in the ALT column if they only store variants, but for some
downstream statistical purposes I am also storing homozygous reference calls in them,
which does put a "." in the ALT column and which is a valid (if uncommon) use.  They were, 
in fact, generated by "bcftools call" with option settings to do so.

Perhaps the fact that a "." is a regex wildcard character is contributing to the problem?

-- Fred P.
</pre>

**Comment by pishotta** [comment] 2015-02-04 17:21
A test file that can be used to demonstrate this behavior can be found here:

> http://ubccan-public.can.ubc.ca/download/test.vcf.gz

**Comment by pd3** [comment] 2015-02-05 08:41
Thank you for the test case, now fixed.

**Closed** 2015-02-05 08:41 UTC

**Comment by pishotta** [comment] 2015-02-05 16:08
That fixed most things, thanks.  No segfaults, but

>> bcftools view -i 'alt="."' test.vcf.gz

still fails to return rows where there is a “.” in the ALT column of the vcf file.
Thought it might be an “escape” problem on the command line (bash), but
various versions of putting back-slashes before the dot, didn’t help.

Test file is still at http://ubccan-public.can.ubc.ca/download/test.vcf.gz

-- Fred P.

**Comment by jmarshall** [comment] 2015-02-09 13:57
In file included from faidx.c:33:
    htslib/faidx.h:94: error: wrong number of arguments specified for ‘__deprecated__’ attribute

This borkage has now been fixed on htslib's **develop** by samtools/htslib@a233385648d1b7f2490106a5b6e09c0baa53abd4.
