### ISSUE TITLE
extracting regions causes adjacent snp/indels to be out of order

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#384] opened 2016-02-24 01:54 UTC
I ran into an issue where extracting regions resulted in an out of order vcf. Specifically, snps being mixed up with adjacent indels. The input regions were sorted and merged so that wasn't the problem. The issue seems to be related indels having variable end positions and therefore it's possible to match the same indel both before and after a snp.

Not sure if it's expected but it confused me for a bit. Notably, bedtools got the order right.

[tmp1.vcf.gz](https://drive.google.com/file/d/0B5pgT9nmbwfSSHdfbHZ6RzNFZUk/view?usp=sharing)
[tmp2.bed.gz](https://drive.google.com/file/d/0B5pgT9nmbwfSc1JWb2h1NWRmUkk/view?usp=sharing)

```
# bcftools out of order
bcftools view tmp1.vcf.gz -H -R tmp2.bed  

# bedtools order maintained
bedtools intersect -a tmp1.vcf.gz -b tmp2.bed
```

**Comment by mcshane** [comment] 2016-02-24 09:23
Thanks for the test case @dwaggott. This is a know issue. Closing as a duplicate of #221. One non-ideal work around is to use `-T` rather than `-R`.

**Closed by mcshane** 2016-02-24 09:23 UTC

**Comment by pd3** [comment] 2019-11-07 15:46
Hopefully this should be fixed by https://github.com/samtools/htslib/commit/db90fb58b06d6f3b27b5b873588da7c77844da22. Can you please try it out?
