### ISSUE TITLE
trying to understand *missense annotation

### ISSUE THREAD

**Issue by jel4h** [samtools/bcftools#1342] opened 2020-11-11 01:52 UTC
Can you please explain the * in the annotation output?... I found this in the documentation:

```
 # The consequence type of a variant downstream from a stop are prefixed with *
    BCSQ=*missense|PER3|ENST00000361923|+|1028M>1028T|7890117T>C
```

but I don't know how far downstream the variant is from a stop.   In the times I encountered *<impact> in my output, the variants were FAR away from a stop - like >50 amino acids away.

**Comment by pd3** [comment] 2020-11-12 12:56
The documentation seems to be consistent with the behavior and a stop upstream is important regardless of how many amino acids away it is?

To help decide whether the program is doing the correct thing, a small reproducible test case would be necessary.

**Comment by jel4h** [comment] 2020-11-13 22:26
Ok, I think I figured it out... here's an example in my output where 1 variant maps to 2 different transcripts for the same gene (gene id redacted).   One variant is called 'missense' and another is called '*missense'

7	112548652	D9261_7_112548652_A	T	A	60	.	QNAME=7;QSTART=101208891;QSTRAND=+;BCSQ=missense|GeneXXX|GeneXXX_T001|protein_coding|+|71S>71T|112548652T>A,*missense|GeneXXX|GeneXXX_T003|protein_coding|+|350S>350T|112548652T>A

I looked at the other variants mapping to these transcripts and there is a predicted stop_gained variant upstream of the *missense variant but not for the missense variant.

I think my confusion was in the vagueness of the documentation.   I assumed it meant the native stop codon, not a new stop codon from an adjacent variant.

**Comment by pd3** [comment] 2020-11-17 14:59
A new stop codon itself is marked as `stop_gained`. This is useful to alert about variants downstream of a new stop codon which may or may not be valid.

**Closed by pd3** 2020-11-17 14:59 UTC
