### ISSUE TITLE
Segmentation fault with bcftools +dosage 

### ISSUE THREAD

**Issue by npatel22526** [samtools/bcftools#813] opened 2018-06-14 20:04 UTC
Hello,

I was trying to obtain dosage using bcftools plugins but it's keep exiting with Segmentation fault.  I am using bcftools 1.8

I trace back the error and identified the culprit to be a samples with   "GT:AD:DP:GQ:PL ./.:0,0:0:.:."  So missing genotype with zero read depth seems to be the issue.

If there a work around to this ?  Also is there a away to output dosage information as VCF and not bed file.  

Best, 
Nick

**Comment by pd3** [comment] 2018-06-15 20:30
Hi Nick, thank you for reporting the problem. I am not able to reproduce it though. Any chance you could provide a small test case to reproduce the segfault?

**Comment by npatel22526** [comment] 2018-06-15 20:41
Thanks for getting back. 

Actually issue seems to be something else , I tried to remove all annotation except GT and PL ans it still happened. 

See attached file , error occurs at 1:10396
[dosageTest.temp.vcf.gz](https://github.com/samtools/bcftools/files/2107426/dosageTest.temp.vcf.gz)

Best, 
Nick

**Comment by pd3** [comment] 2018-06-16 09:30
I am still unable to reproduce the bug, tried with 1.8 and the latest github source. Can you try to recompile as described here http://samtools.github.io/bcftools/ and see if it changes anything?

**Comment by npatel22526** [comment] 2018-06-19 14:45
Sorry for late response , so I recompiled error went away with previously attached file. 
However when I ran with complete file got error at another position. Also error only occurs while calculating dosage with PL. 
The updated File : 
[dosageTest.temp.vcf.gz](https://github.com/samtools/bcftools/files/2115681/dosageTest.temp.vcf.gz)

My commands 
No error 
> bcftools plugin dosage dosageTest.temp.vcf.gz -- -t GT   > test.gt.txt

Error at chr1:54708
> bcftools plugin dosage dosageTest.temp.vcf.gz -- -t PL   > test.PL.txt

**Comment by pd3** [comment] 2018-06-19 22:29
Thank you for the updated test. The segfault is caused by the program's unchecked assumption that there are no multiallelic sites. As a quick workaround you can run the command with `-i 'N_ALT<=2'` to exclude sites with mutliple alternate alleles.
I am not sure how to fix this properly for multiallelic sites - skip them, take the first allele, or maybe print a comma-separated dosages for all alleles.

**Comment by npatel22526** [comment] 2018-06-20 14:09
That's awesome. Thanks for all your help.
I did not wanted to exclude any sites so normalizing VCF did the trick. 
> bcftools norm -m - dosageTest.temp.vcf.gz | bcftools plugin dosage  -- -t PL > dosage.pl.txt

Best, 
Nick

**Comment by pd3** [comment] 2018-06-22 13:20
OK. This is now fixed to output dosages for all alternate alleles and does not segfault on your test anymore. Thanks for the bug report.

**Closed** 2018-06-22 13:19 UTC

**Comment by pd3** [comment] 2018-08-01 10:17
This commit introduced bugs, as reported by https://github.com/samtools/bcftools/issues/851. Now fixed by 34a5b0d.
