### ISSUE TITLE
-types snps not working

### ISSUE THREAD

**Issue by dwaggott** [samtools/bcftools#257] opened 2015-05-08 17:50 UTC
I tried using `bcftools view -v snps` and it none of the indels were filtered. Conversely, if I use `-e TYPE="snp"` it works. Does that make sense?

**Comment by mcshane** [comment] 2015-05-11 13:39
Sorry, I can't reproduce. Can you send an example?

**Comment by mcshane** [comment] 2015-10-22 09:39
I'm going to close this since I can't reproduce. Please reopen if you can supply an example.

**Closed by mcshane** 2015-10-22 09:39 UTC
Labels: bug, need-feedback
