### ISSUE TITLE
bcftools consensus giving inconsistent results

### ISSUE THREAD

**Issue by sowmyaiyer** [samtools/bcftools#1149] opened 2020-01-31 15:47 UTC
If I run the following command

`bcftools consensus -H A -f testrun_faidx_out2.txt --sample HG00105 small_test.vcf.gz`

I get the following correct output (note three additional bases for 14:43616643-43616665 corresponding to insertion in HG00105) 

```
>14:43263973-43263995
GAGGGTGAGCAGAAGCAGGGTGG
>14:43308392-43308414
CCTTTCTTTCCTGCTCTGAAGCT
>14:43442685-43442707
CCCGTCTTCTTCGTTGCTCAGGC
>14:43616643-43616665
GAGTGGGAGCTGAAGAAGAAGTAGAT
```

If I run the same command with this input file which is the same as before but with an additional fasta entry after 14:43616643-43616665

`bcftools consensus -H A -f testrun_faidx_out1.txt --sample HG00105 small_test.vcf.gz`

I get this different output (see entry for 14:43616643-43616665 not having the inserted bases, but instead the reference sequence)

```
>14:43263973-43263995
GAGGGTGAGCAGAAGCAGGGTGG
>14:43308392-43308414
CCTTTCTTTCCTGCTCTGAAGCT
>14:43442685-43442707
CCCGTCTTCTTCGTTGCTCAGGC
>14:43616643-43616665
GAGTGGGAGCTGAAGAAGTAGAT
>14:44474477-44474499
GAGGAGGAGGAGAAGAAGAAGAA
```

[small_test.vcf.gz](https://github.com/samtools/bcftools/files/4145792/small_test.vcf.gz)
[testrun_faidx_out1.txt](https://github.com/samtools/bcftools/files/4140188/testrun_faidx_out1.txt)
[testrun_faidx_out2.txt](https://github.com/samtools/bcftools/files/4140189/testrun_faidx_out2.txt)

> bcftools --version
bcftools 1.9
Using htslib 1.9

**Comment by sowmyaiyer** [comment] 2020-02-04 16:59
Hi, was anyone able to reproduce the error with the test files?

**Comment by pd3** [comment] 2020-02-05 13:20
Hi, yes, I was able to reproduce the error.

It is a tricky situation, your test case highlights a problem discussed at length in https://github.com/samtools/hts-specs/pull/464. In your case the <CN0> symbolic allele overlaps a subsequent variant via the INFO/END position. The question is whether it should be interpreted as conflicting and skipped, or whether it should be applied. (I am aware that in this particular case the copy number state is not in conflict with the insertion and therefore should be applied, but the program is not that smart. It just sees a symbolic variant of certain length and does not distinguish between different types.)

Fortunately there is a simple solution for you: add the `-e 'ALT~"<.*>"'` filtering expression to exclude all symbolic alleles.


Then there is the question why the variant was applied in one case but not in the other. This comes to one subtlety in the code and the fact that your fasta file has multiple short sequences rather than a single chromosome block. I'll explore if this can be changed to give a consistent behavior. 

Another change we can do in the program is to change the interpretation of the 0/0 genotype to mean "the reference genotype, unless other alternate allele downstream is applied". 

Lastly, we could make the program ignore CN and possibly other symbolic alleles altogether. However, since the same can be achieved using the filtering expression show above, I think it is better to leave the default as is. This way the user can choose, sometimes one may prefer one behavior over the other.

**Comment by sowmyaiyer** [comment] 2020-02-05 16:58
Thank you for the detailed explanation. I will use the exclude filter and yes, consistent output would be helpful. Thanks again.

**Comment by pd3** [comment] 2020-02-06 21:27
This should be now fixed, please let me know in case of you spot any other problems.

**Closed** 2020-02-06 21:26 UTC
Labels: bug
