### ISSUE TITLE
bcftools mpileup --max-depth

### ISSUE THREAD

**Issue by Silvia-lme** [samtools/bcftools#1392] opened 2021-02-01 22:11 UTC
According to the manual a default for the --max-depth is 250, which mean that only 250 reads per-file are considered at a position.

Please could somebody explain me how it works when I am using one multi-sample bam file (merge file of 130 samples). Does it work with all 130 individuals or it stop when it reach 250 reads at position, doesn't matter that it counted only e.g. first 10 individuals (when e.g. each individual have 25 reads at particular position).

**Comment by pd3** [comment] 2021-02-02 07:47
This is a duplicate of https://github.com/samtools/bcftools/issues/1389

**Closed by pd3** 2021-02-02 07:47 UTC
