### ISSUE TITLE
bcftools isec misses sites depending on input order

### ISSUE THREAD

**Issue by rsteinfe1** [samtools/bcftools#751] opened 2018-03-01 20:42 UTC
Hi,

I'm using bcftools to intersect 3 vcf files from different somatic variant callers (Strelka, VarScan2, VarDict). Since I've noticed that none of the callers are perfect, I figured that a majority vote between all three callers works best assuming decent filtering of the resulting candidates. 
Now, in the past I've been using vcftools for this, but it's increasingly frustrating working with vcftool's output, since info and sample columns are somewhat randomly picked from source input leaving incomparable vcf files. Hence, I'm looking for a suitable alternative. 
While I was looking at bcftools I compared the results. Here's an minimal example:

strelka.vcf:
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr17	56492873	.	C	CT	.	PASS	QSI=238;TQSI=1;NT=ref;QSI_NT=130;TQSI_NT=1;SGT=ref->het;RU=T;RC=1;IC=2;IHP=2;SOMATIC	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50	132:132:132,133:0,0:0,0:147.79:0.0:0.0	140:140:74,74:66,67:0,0:223.53:0.0:0.0

varscan2.vcf(empty):
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR

vardict.vcf:
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr17	56492873	.	C	CT	185.0	PASS	TYPE=Insertion;SHIFT3=1;MSI=2.0;MSILEN=1.0;SSF=0.0;SOR=inf;LSEQ=CCTGTGCGTCCAAAGCCTGC;RSEQ=TGCAGGGTAGCCATCAGCAG;STATUS=StrongSomatic	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	0/1:141:67:34,33:37,37:74,67:0.4752:2,2:43.0:1.0:30.5:1.0:1.0:1.03:60.3:66.0:0.4783:0.0:0.2	0/0:133:0:0,0:68,65:133,0:0.0:2,0:42.6:1.0:31.7:1.0:1.0:0.0:60.0:65.5:1.0:0.0:0.2

I'm now trying to get the majority vote, so mutation chr17:56492873_C/CT should be reported. vcf-isec does that correctly and prints strelka's output:
> vcf-isec -a -f -n +2 varscan2.vcf.gz strelka.vcf.gz vardict.vcf.gz
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr17	56492873	.	C	CT	.	PASS	QSI=238;TQSI=1;NT=ref;QSI_NT=130;TQSI_NT=1;SGT=ref->het;RU=T;RC=1;IC=2;IHP=2;SOMATIC;SF=1,2	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50	132:132:132,133:0,0:0,0:147.79:0.0:0.0	140:140:74,74:66,67:0,0:223.53:0.0:0.0

Little side note: if you change the order and swap strelka.vcf.gz with vardict.vcf.gz it would print vardict's output instead.

Now, if I run it with bcftools isec instead, the output is empty:
> bcftools isec varscan2.vcf.gz strelka.vcf.gz vardict.vcf.gz -n +2 -w 1 -c none -f PASS
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR

unless (!) I change the order again: 
> bcftools isec strelka.vcf.gz vardict.vcf.gz varscan2.vcf.gz vardict.vcf.gz -n +2 -w 1 -c none -f PASS
##fileformat=VCFv4.1
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr17	56492873	.	C	CT	.	PASS	QSI=238;TQSI=1;NT=ref;QSI_NT=130;TQSI_NT=1;SGT=ref->het;RU=T;RC=1;IC=2;IHP=2;SOMATIC	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50	132:132:132,133:0,0:0,0:147.79:0:0	140:140:74,74:66,67:0,0:223.53:0:0

Is it possible that bcftools isec can perform the intersection correctly 
and (if posssible) combines the info/format/sample fields and sets unavailable fields to empty/NA/. ?
That would be an amazing help.

I was using bcftools 1.7

Thanks,
 Robert

**Comment by pd3** [comment] 2018-03-19 10:56
Hi, the program is behaving correctly. By giving the `-w 1` option you requested that only sites from the first file are output. But the `varscan2.vcf` is empty, so nothing is printed. Consider using the `-p` option perhaps?

Thank you for the report, I am closing the issue now. Please reopen if you think the problem is not resolved.

**Closed by pd3** 2018-03-19 10:56 UTC
