### ISSUE TITLE
bedtools consensus

### ISSUE THREAD

**Issue by khuhu** [samtools/bcftools#991] opened 2019-03-22 18:56 UTC
Hi,

I ran into a problem another user recently posted using the consensus function. I followed the advice provided by downloading the github development version (Version: 1.9-117-g9e81e92), but I still run into the same error. The fasta output is cutoff where the first variant lies. Below is command, error and files I used. Changed the .fa suffix to .txt since it wouldn't upload the file type. 

[2405n.vcf.gz](https://github.com/samtools/bcftools/files/2997879/2405n.vcf.gz)
[mm10.IAD124056_167.txt](https://github.com/samtools/bcftools/files/2997887/mm10.IAD124056_167.txt)

`./bcftools consensus -f /mnt/DATA4/kevhu/ComprehensiveMouse/fastas/mm10.IAD124056_167.fa /mnt/DATA4/kevhu/ComprehensiveMouse/vcfs/2405n.vcf.gz -o /mnt/DATA4/kevhu/ComprehensiveMouse/fastas/20190322consensusTest.fa
`

`Note: the --sample option not given, applying all records regardless of the genotype`
`The fasta sequence does not match the REF allele at chr2:165791933:`
`   .vcf: [A] <- (REF)`
`   .vcf: [G] <- (ALT)`
`.fa:  [G]AGGAGGGCG`

 Hope I provided the necessary information,
Kevin

**Comment by pd3** [comment] 2019-03-22 21:11
The program seems to be doing the correct thing. The position chr2:165791933 in the fasta has G whereas the VCF says A. I am closing the issue as it's not a bug.

**Closed by pd3** 2019-03-22 21:11 UTC

**Comment by khuhu** [comment] 2019-03-22 21:33
Sorry, misread the error message. Thanks!
