### ISSUE TITLE
bcftools merge -m snps sets variant sites that are homozygote refs as missing

### ISSUE THREAD

**Issue by dgurdasani** [samtools/bcftools#408] opened 2016-04-12 15:27 UTC
I've just noticed using bcftools 1.3 merge - merging two samples, sites that are 0/0  in the first sample and 0/1 in the second sample end up as ./. in the first sample and 0/1 in the second during the merge  My script is below:

/software/hgi/pkglocal/bcftools-1.3/bin/bcftools merge -m snps /lustre/scratch114/projects/hgdp_wgs/resources/simons-genome-diversity-project/SGDP/samples/FullyPublicHGDP/VCFS/LP6005442-DNA_B02.${K}.filtered.vcf.gz /lustre/scratch114/projects/hgdp_wgs/resources/simons-genome-diversity-project/SGDP/samples/FullyPublicHGDP/VCFS/LP6005441-DNA_A05.${K}.filtered.vcf.gz   |  fgrep -v "#"   |  awk '{if ($5!=".") print $0}' | awk '{print $1, $2, $4, $5, $10, $11}' > mergeYRIFrench${K}.vcf

Here's an example of such a site. In the first sample:
 1	234378	.	A	.	56.99	.	AN=2;BaseCounts=54,0,1,0;DP=55;GC=49.63;MQ=14.19;MQ0=33;FL=-1	GT:DP	0/0:53

In the merged file, the first genotype field appears as ./.

1       234378  rs200864529     A       G       36.01   .       BaseCounts=45,0,10,0;BaseQRankSum=-0.364;DB;Dels=0;FS=0;GC=49;HaplotypeScore=0;MQ=17.75;MQ0=27;MQRankSum=-0.98;QD=0.65;ReadPosRankSum=-0.868;FL=-1;DP=55;AF=0.5;MLEAC=1;MLEAF=0.5;AN=2;AC=1     GT:AD:DP:GQ:PL  ./.:.:.:.:.     0/1:45,10:53:36:36,0,512

I would really appreciate if you could fix this.

Thanks.

Best wishes,
Deepti

**Comment by pd3** [comment] 2016-04-13 06:56
I was not able to reproduce the error. Assuming K=1, this gives the expected output:

      A=/lustre/scratch114/projects/hgdp_wgs/resources/simons-genome-diversity-project/SGDP/samples/FullyPublicHGDP/VCFS/LP6005442-DNA_B02.1.filtered.vcf.gz
      B=/lustre/scratch114/projects/hgdp_wgs/resources/simons-genome-diversity-project/SGDP/samples/FullyPublicHGDP/VCFS/LP6005441-DNA_A05.1.filtered.vcf.gz

      bcftools merge -m snps $A $B | bcftools query -f '%POS [ %GT]\n' | awk '$1==234378'
      234378  0/0 0/1

**Comment by dgurdasani** [comment] 2016-04-13 09:20
Hi Petr,

Are you using the same version that I used:


/software/hgi/pkglocal/bcftools-1.3/bin/bcftools



I noticed this error has been reported before, so maybe it’s been fixed in a later version?


Best wishes,

Deepti

**Comment by mcshane** [comment] 2016-04-13 14:13
Hi Deepti. There are a bunch of merge bugfixes and features waiting to be pull into the main repo. In the meantime you can use Petr's experimental version at http://pd3.github.io/bcftools/ which contain the fixed you want for this. You'll need to follow the instructions to clone and compile there.

**Comment by dgurdasani** [comment] 2016-04-13 15:02
Hi Shane,

Thanks! Will do that.

Best wishes,
Deepti

**Comment by mcshane** [comment] 2016-08-07 19:08
This should be resolved now that #455 has been merged.

**Closed by mcshane** 2016-08-07 19:08 UTC
