### ISSUE TITLE
bcftools norm left-align create wrong duplicated variants

### ISSUE THREAD

**Issue by edg1983** [samtools/bcftools#1585] opened 2021-09-24 14:40 UTC
Hello, 
I've found this issue when running bcftools norm (v.1.11, 1.12 and 1.13), specifically in the left-align function. I think this can be the same also reported in #1379.

Essentially here is an example, using my cohort VCF generated by DeepVariant + GLNexus.
The raw VCF variants look like this (just first 5 columns):
```
chr10   54031553        chr10_54031553_G_GA     G       GA
chr10   54031556        chr10_54031556_A_AC;chr10_54031556_A_AA A       AC,AA
```

Then I use bcftools to split multi-allelics `bcftools norm -m- -Oz -o splitted.vcf.gz raw.vcf.gz` and all looks fine
```
chr10   54031553        chr10_54031553_G_GA     G       GA
chr10   54031556        chr10_54031556_A_AC;chr10_54031556_A_AA A       AC
chr10   54031556        chr10_54031556_A_AC;chr10_54031556_A_AA A       AA
```

Now when I apply norm and left-align using `bcftools norm -f GRCh38.fa -Oz -o norm.vcf.gz splitted.vcf.gz` and the second variant is wrongly altered and becomes the same as the previous variant
```
chr10   54031553        chr10_54031553_G_GA     G       GA
chr10   54031553        chr10_54031556_A_AC;chr10_54031556_A_AA G       GA
chr10   54031556        chr10_54031556_A_AC;chr10_54031556_A_AA A       AC
```

The same happens if I run both operations in the same command using `bcftools norm -m- -f GRCh38.fa -Oz -o norm.vcf.gz raw.vcf.gz`

I've attached my raw VCF with just these 2 vars if want to reproduce the error.

Let me know if there is a fix for this!
Thank
[test_var.vcf.gz](https://github.com/samtools/bcftools/files/7226520/test_var.vcf.gz)

**Comment by edg1983** [comment] 2021-09-24 15:39
Just an update on the above. 
The odd behavior do not seem related to multi-allelic variants, but just to specific variants. Indeed if I create a VCF with only 
```
chr10   54031553        chr10_54031553_G_GA     G       GA
chr10   54031556        chr10_54031556_A_AA A       AA
```
I see the same error.

**Comment by edg1983** [comment] 2021-09-24 17:02
Actually, I've realized that this is kind of reasonable in term of the variant representation.
This locus has  a G at 54031553, followed by a stretch of A, so the variant 
```
chr10   54031556        chr10_54031556_A_AA A       AA
```
represents the insertion of an A in the stretch, which can be represented by 
```
chr10   54031553        chr10_54031553_G_GA     G       GA
```
when aligning to the leftmost position.

Even if this can be considered correct in terms of the sequence, such behavior creates 2 duplicated variants with different sample genotypes and this can create troubles downstream. However, I don't know if there is any way to fix this besides dropping the duplicated vars completely. This can be acceptable in most cases I think since they are mostly artifacts from homopolymers / lowcomplexity I suppose.

**Comment by pd3** [comment] 2021-09-25 14:37
That is correct. At the sequence level we can't really tell which of the A's was inserted, therefore we trim indels and align them to the left whenever possible.  To remove duplicates created by splitting multiallelics, one can do
```
bcftools norm -m - -f ref.fa test.vcf -Ou | bcftools norm -d exact
```
From this perspective the program works as intended, so I will close the issue now.

**Closed by pd3** 2021-09-25 14:37 UTC
