### ISSUE TITLE
bcftools: vcfnorm.c:706: split_info_numeric: Assertion `ret==src->n_allele-1' failed.

### ISSUE THREAD

**Issue by angelcymak** [samtools/bcftools#364] opened 2015-12-24 22:44 UTC
Hi,

The bcftools version I am using is:
bcftools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.

I ran:
bcftools annotate -Ou $indir/$fI.vcf.gz | bcftools norm -Ov -m -any

I am getting this error:
bcftools: vcfnorm.c:706: split_info_numeric: Assertion `ret==src->n_allele-1' failed.

Could you please give me some suggestions on how to resolve this?

Thanks,
Angel

-----
I think it was having trouble with this line:
1	2523041	.	GCGAACTCGGGCCGGTA	GGGGCCGGTA,G	828.58	Indel_FS;Indel_QD;Indel_ReadPosRankSum	AC=4,2;AF=0.0278;AN=232;BaseQRankSum=-1.537;DP=43139;FS=3200.000;HRun=0;HaplotypeScore=1408.4493;InbreedingCoeff=-0.0286;MQ0=1;MQ=59.37;MQRankSum=3.147;QD=0.89;ReadPosRankSum=-54.159;SF=0f,1f;SNPEFF_EFFECT=FRAME_SHIFT;SNPEFF_EXON_ID=exon_1_2522996_2523072;SNPEFF_FUNCTIONAL_CLASS=NONE;SNPEFF_GENE_BIOTYPE=processed_transcript;SNPEFF_GENE_NAME=MMEL1;SNPEFF_IMPACT=HIGH;SNPEFF_TRANSCRIPT_ID=ENST00000288709	GT:GQ:DP:PL:AD	0/0:99:245:.,.,24344,.,.,.:245,0	0/0:99:233:.,.,20057,.,.,.:233,0	0/0:99:176:.,.,13514,.,.,.:176,0	0/0:99:264:.,.,26862,.,.,.:264,0	0/0:99:263:.,.,22742,.,.,.:263,0	0/0:99:230:.,.,19560,.,.,.:230,0	0/0:99:242:.,.,22457,.,.,.:242,0	0/0:99:257:.,.,23727,.,.,.:257,0	0/0:99:193:.,.,16889,.,.,.:193,0	0/0:99:208:.,.,17196,.,.,.:208,0	0/0:99:207:.,.,18175,.,.,.:208,0	0/0:99:244:.,.,23819,.,.,.:244,0	0/0:99:274:.,.,26371,.,.,.:274,0	0/0:99:286:.,.,26703,.,.,.:286,0	0/0:99:480:.,.,47357,.,.,.:480,0	0/0:99:157:.,.,13660,.,.,.:157,0	0/1:84.88:189:.,.,14876,.,.,.:189,0	0/0:99:169:.,.,15121,.,.,.:169,0	0/0:66.45:219:.,.,16975,.,.,.:219,0	0/0:99:216:.,.,18318,.,.,.:216,0	0/0:99:241:.,.,23159,.,.,.:241,0	0/0:99:217:.,.,19437,.,.,.:217,0	0/0:67.08:226:.,.,16281,.,.,.:173,53	0/0:99:263:.,.,23924,.,.,.:263,0	0/0:99:303:.,.,28389,.,.,.:303,0	0/0:99:218:.,.,20610,.,.,.:218,0	0/0:99:335:.,.,31507,.,.,.:335,0	0/0:99:253:.,.,19393,.,.,.:253,0	0/0:99:258:.,.,23528,.,.,.:258,0	0/0:99:253:.,.,22766,.,.,.:253,0	0/0:99:229:.,.,21811,.,.,.:229,0	0/0:99:46:.,.,4478,.,.,.:46,0	0/0:99:206:.,.,20880,.,.,.:211,0	0/0:99:243:.,.,20604,.,.,.:243,0	0/0:99:237:.,.,20750,.,.,.:237,0	0/0:83.55:194:.,.,16538,.,.,.:194,0	0/0:99:238:.,.,21359,.,.,.:240,0	0/0:99:245:.,.,23726,.,.,.:245,0	0/0:99:219:.,.,16358,.,.,.:219,0	0/0:99:280:.,.,21749,.,.,.:280,0	0/0:99:175:.,.,17089,.,.,.:175,0	0/0:99:307:.,.,26432,.,.,.:269,0	0/0:99:323:.,.,29072,.,.,.:323,0	0/0:38.52:153:.,.,11822,.,.,.:153,0	0/0:99:248:.,.,24810,.,.,.:248,0	0/0:99:239:.,.,22132,.,.,.:240,0	0/0:99:196:.,.,15679,.,.,.:196,0	0/0:99:245:.,.,23395,.,.,.:245,0	0/0:99:205:.,.,18419,.,.,.:205,0	0/1:99:135:.,.,8876,.,.,.:135,0	0/0:42:173:.,.,11820,.,.,.:174,0	0/1:99:143:.,.,6684,.,.,.:143,0	0/0:99:249:.,.,20797,.,.,.:249,0	0/1:99:233:.,.,16369,.,.,.:233,0	0/0:45.60:157:.,.,10851,.,.,.:158,0	0/0:99:229:.,.,20731,.,.,.:229,0	0/0:99:224:.,.,23170,.,.,.:226,0	0/0:99:299:0,.,.,630,.,48266:299,0	0/0:99:191:0,.,.,281,.,25388:191,0	0/0:99:172:0,.,.,170,.,23100:172,0	0/0:99:248:0,.,.,434,.,33266:249,0	0/0:99:232:0,.,.,507,.,39062:232,0	0/0:99:202:0,.,.,197,.,28923:203,0	0/0:99:210:0,.,.,396,.,33670:210,0	0/0:99:261:0,.,.,407,.,42300:261,0	0/0:99:253:0,.,.,562,.,44909:253,0	0/0:99:189:0,.,.,189,.,24408:189,0	0/0:99:314:0,.,.,265,.,45470:254,60	0/0:13.61:239:0,.,.,14,.,30652:239,0	0/0:99:174:0,.,.,166,.,18864:174,0	0/0:99:213:0,.,.,367,.,33346:214,0	0/0:99:205:0,.,.,252,.,27505:206,0	0/0:99:235:0,.,.,361,.,33196:235,0	0/0:99:256:0,.,.,464,.,42221:257,0	0/0:99:249:0,.,.,467,.,40653:249,0	0/0:99:213:0,.,.,335,.,34009:214,0	0/0:31.06:198:0,.,.,31,.,24384:198,0	0/0:99:197:0,.,.,325,.,31193:197,0	0/0:99:285:0,.,.,395,.,41705:285,0	0/0:99:318:0,.,.,546,.,50254:318,0	0/0:99:229:0,.,.,575,.,39219:229,0	0/0:99:264:0,.,.,503,.,43638:264,0	0/0:99:202:0,.,.,220,.,27267:202,0	0/0:99:461:0,.,.,724,.,71574:461,0	0/0:99:182:0,.,.,393,.,31007:182,0	0/0:99:285:0,.,.,640,.,49584:285,0	0/0:99:271:0,.,.,673,.,45786:272,0	0/0:99:250:0,.,.,463,.,39157:250,0	0/0:99:259:0,.,.,568,.,44627:259,0	0/0:99:236:0,.,.,287,.,35860:205,33	0/0:6.37:145:0,.,.,6,.,13268:145,0	0/2:99:397:275,.,.,0,.,57871:397,0	0/0:94.92:194:0,.,.,95,.,26396:194,0	0/0:83.02:218:0,.,.,83,.,28617:218,0	0/0:85.33:165:0,.,.,85,.,21057:165,0	0/0:99:223:0,.,.,402,.,33975:223,0	0/0:99:228:0,.,.,426,.,35169:228,0	0/0:99:196:0,.,.,338,.,25746:196,0	0/0:99:203:0,.,.,380,.,29895:203,0	0/0:99:238:0,.,.,297,.,37029:239,0	0/0:99:251:0,.,.,176,.,37372:251,0	0/0:99:268:0,.,.,595,.,41380:268,0	0/0:99:98:0,.,.,259,.,17275:98,0	0/0:99:361:0,.,.,561,.,53642:361,0	0/0:99:291:0,.,.,377,.,44295:293,0	0/0:99:257:0,.,.,177,.,36220:257,0	0/0:99:251:0,.,.,346,.,40119:252,0	0/0:99:230:0,.,.,560,.,43542:230,0	0/0:99:241:0,.,.,363,.,34371:241,0	0/2:99:478:191,.,.,0,.,70573:485,0	0/0:99:201:0,.,.,279,.,32725:201,0	0/0:99:221:0,.,.,568,.,39477:221,0	0/0:99:429:0,.,.,920,.,73213:429,0	0/0:99:199:0,.,.,300,.,32015:199,0	0/0:99:335:0,.,.,651,.,52926:336,0	0/0:99:259:0,.,.,677,.,44479:261,0

bcftools: vcfnorm.c:706: split_info_numeric: Assertion `ret==src->n_allele-1' failed.

**Comment by pd3** [comment] 2016-01-11 12:38
Hi Angel, in general, these types of errors are usually triggered by VCF non-conforming to the specification, most often incorrect number of fields. This is hard to tell without seeing the full headers. Any chance you could provide a small test file to reproduce the error? There is an email address on my profile page. Thanks

**Comment by darked89** [comment] 2016-03-22 17:10
I got the same type of error using as an input VCF file produced by freeBayes v1.0.2-6 while running bcftools norm. Lines containing 2 alternative alleles separated by coma trigger the same assertion error:
'''
2	62035409	.	ATTTTTTTTTTTTTTTTG	ATTATTTTTTTTTTTTG,ATTTTTTTTTTTTTG
''' 
I guess it has to be fixed on the freeBayes side. In a meanwhile a hack to simply process the VCF and get an idea what these tricky calls looks like one can simply split the above one line into:
'''
2	62035409	.	ATTTTTTTTTTTTTTTTG	ATTATTTTTTTTTTTTG
2	62035409	.	ATTTTTTTTTTTTTTTTG	ATTTTTTTTTTTTTG
''' 
keeping the remaining columns as these were in original line. Not a workable solution for any subsequent steps. 

Darek Kedra

**Comment by pd3** [comment] 2016-03-23 07:51
Thank you for the test case you sent me offline. The problem is indeed in incorrect number of values in the FMT/DPR annotation which should be defined as `Number=R` rather than `Number=A`. 
There are two possible workarounds you could do: 1) modify the header (`bcftools reheader`) to reflect the uncertainty, changing `Number=A` to `Number=.`.  2) drop the offending field altogether (`bcftools annotate -x FMT/DPR`).
I have pushed a version which will give more informative message on errors like this.

**Closed** 2016-04-29 15:12 UTC
Labels: needs-feedback
