### ISSUE TITLE
[E::bcf_sr_regions_init] Could not parse the file mylist.txt, using the columns 1,2[,-1]

### ISSUE THREAD

**Issue by montenegrina** [samtools/bcftools#1201] opened 2020-04-13 19:41 UTC
Hello,

I was running this command:

     $ bcftools view -R mylist.txt gokind2.bcf -Ou -o filteredfile.bcf

where mylist.txt was a tab separated file:

   20  33371323
    12  73950313
    1   216957281

but I got this error:

    [E::bcf_sr_regions_init] Could not parse the file mylist.txt, using the columns 1,2[,-1]
    Failed to read the targets: mylist.txt

     cat -te mylist.txt

gives me:

    20^I33371323$
    12^I73950313$
    1^I216957281$
    5^I174820027$
    ...

    bcftools --version
    bcftools 1.10.2-32-ge677391
    Using htslib 1.10.2-46-g9a10355
    Copyright (C) 2019 Genome Research Ltd.

Please advise,
Ana

**Comment by pd3** [comment] 2020-04-14 08:27
I am unable to reproduce the problem. Most likely your file is truncated, verify if the number of columns is the same in the entire file e.g with
```
cat mylist.txt | awk -F\\t '{print NF}' | sort | uniq -c
```

**Comment by montenegrina** [comment] 2020-04-14 15:06
it's this

$ cat mylist.txt | awk -F\\t '{print NF}' | sort | uniq -c
 364869 2

**Comment by pd3** [comment] 2020-04-14 15:09
Can you share the data / create a small reproducible test case to debug the problem?  This is a well tested and widely used feature, very likely a problem with your data.

**Comment by montenegrina** [comment] 2020-04-14 15:16
yes I can do that. Can you please tell me how to extract portion of those
files which would be meaningful for you to test?

$ ls -l --block-size=M gokind2.bcf
-rw-rw-r--. 1 anamaria anamaria 4591M Apr  9 22:09 gokind2.bcf
$ ls -l --block-size=M mylist.txt
-rw-rw-r--. 1 anamaria anamaria 5M Apr 13 12:02 mylist.txt

**Comment by pd3** [comment] 2020-04-22 10:33
I added a new pull request to `htslib` which will print number of the offending line https://github.com/samtools/htslib/pull/1059. The part relevant to this is in https://raw.githubusercontent.com/pd3/htslib/informative_vcf_errors/synced_bcf_reader.c, so if you just download that and recompile `bcftools` and `htslib`, you should be able to isolate the problem.

**Comment by pd3** [comment] 2020-05-18 15:41
This is now on the develop branch, `git pull` in htslib and recompiling bcftools should help. Closing now for lack of further feedback as solved.

**Closed by pd3** 2020-05-18 15:41 UTC
