### ISSUE TITLE
Error with bcftools consensus

### ISSUE THREAD

**Issue by psur9757** [samtools/bcftools#961] opened 2019-02-15 04:34 UTC
I have been trying to extract consensus sequences based on instructions here: https://samtools.github.io/bcftools/howtos/consensus-sequence.html. However I keep getting the following error:
> The fasta sequence does not match the REF allele at 1:77987:
>    .vcf: [C]
>    .vcf: [CCTGTTATTGG] <- (ALT)
>    .fa:  [G]TTGTGATTCATACACTGAGATCTCCT

PBS Script
```
#! /bin/bash
#PBS -P WSRseq
#PBS -N vc_test
#PBS -l select=1:ncpus=1:mem=6G
#PBS -l walltime=6:00:00
#PBS -q defaultQ
#PBS -o run.out
#PBS -e run.err

#load modules needed
module load samtools/1.9
module load bcftools/1.9

# call variants
bcftools mpileup -Ob -o WSR_vc_calls.bcf -f PGTAus-pan.fa WSR_bwa_align_fixmate_sorted_realigned.bam
bcftools call -vmO z -o WSR_vc_calls.vcf.gz WSR_vc_calls.bcf

#normalize indels
bcftools norm -f PGTAus-pan.fa WSR_vc_calls.vcf.gz -Oz -o WSR_vc_calls.norm.vcf.gz

# filter adjacent indels within 5bp
bcftools filter --IndelGap 5 WSR_vc_calls.norm.vcf.gz -Oz -o WSR_vc_calls.flt-indels.vcf.gz

#filter low quality reads
bcftools filter -s LOWQUAL -e '%QUAL<20 || DP>100' WSR_vc_calls.flt-indels.vcf.gz -Oz -o WSR_vc_calls.flt-indels-lq.vcf.gz

#index vcf file
bcftools index WSR_vc_calls.flt-indels-lq.vcf.gz

#get consensus sequence
cat PGTAus-pan.fa | bcftools consensus WSR_vc_calls.flt-indels-lq.vcf.gz > WSR_consensus.fa
```

I have also tried changing the order of steps (call -> filter -> normalize) but still get the same error.

**Comment by pd3** [comment] 2019-02-15 12:37
I believe this has been already fixed. Can you try with the latest version from github? Please see the install instructions here http://samtools.github.io/bcftools/ and here http://samtools.github.io/bcftools/howtos/install.html.

**Comment by psur9757** [comment] 2019-02-17 22:21
Hi Peter,

bcftools 1.9 is the latest version and I checked with our HPC team, it has been installed according to instructions. I am really not sure what I am doing wrong. Thank you.

**Comment by mp15** [comment] 2019-02-17 23:00
1.9 is the latest released version but version on github is all development since the 1.9 release. I would suggest you ask your HPC team to compile it for you.

**Comment by pd3** [comment] 2019-12-28 14:24
I am closing this issue as it appears unconfirmed with the latest development version.

**Closed** 2019-12-28 14:23 UTC

**Comment by tseemann** [comment] 2020-02-21 01:18
@pd3 this is still happening with `bcftools 1.10.2`
