### ISSUE TITLE
bcftools plugin fill-tags does not work with "-" to read from stdin.

### ISSUE THREAD

**Issue by ghuls** [samtools/bcftools#1165] opened 2020-02-26 11:33 UTC
`bcftools plugin fill-tags` does not want to read from stdin when input filename is set to `-`. It works when not setting it or setting it to `/dev/stdin`. Other plugins seem to allow `-` to read from stdin (or ignore the `-` somehow and default to reading from stdin).

```
$ cat test.bcf | bcftools plugin fill-tags - -- -t 'AF,AC,AN' | head

About: Set INFO tags AF, AC, AC_Hemi, AC_Hom, AC_Het, AN, ExcHet, HWE, MAF, NS
   or custom INFO/TAG=func(FMT/TAG), use -l for detailed description
Usage: bcftools +fill-tags [General Options] -- [Plugin Options]
Options:
   run "bcftools plugin" for a list of common options

Plugin options:
   -d, --drop-missing          do not count half-missing genotypes "./1" as hemizygous
   -l, --list-tags             list available tags with description
   -t, --tags LIST             list of output tags, "all" for all tags
   -S, --samples-file FILE     list of samples (first column) and comma-separated list of populations (second column)

Example:
   # Print a detailed list of available tags
   bcftools +fill-tags -- -l

   # Fill INFO/AN and INFO/AC
   bcftools +fill-tags in.bcf -Ob -o out.bcf -- -t AN,AC

   # Fill all available tags
   bcftools +fill-tags in.bcf -Ob -o out.bcf -- -t all

   # Calculate HWE for sample groups (possibly multiple) read from a file
   bcftools +fill-tags in.bcf -Ob -o out.bcf -- -S sample-group.txt -t HWE

   # Calculate total read depth (INFO/DP) from per-sample depths (FORMAT/DP)
   bcftools +fill-tags in.bcf -Ob -o out.bcf -- -t 'DP=sum(DP)'

$ cat test.bcf | bcftools plugin fill-tags /dev/stdin -- -t 'AF,AC,AN' | head
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AC_Hemi,Number=A,Type=Integer,Description="Allele counts in hemizygous genotypes">
##INFO=<ID=AC_Het,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes">
##INFO=<ID=AC_Hom,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency">
##INFO=<ID=ALTCOUNT,Number=1,Type=Integer,Description="Alternative Allele Count">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">

$ cat test.bcf | bcftools plugin fill-tags -- -t 'AF,AC,AN' | head
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AC_Hemi,Number=A,Type=Integer,Description="Allele counts in hemizygous genotypes">
##INFO=<ID=AC_Het,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes">
##INFO=<ID=AC_Hom,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency">
##INFO=<ID=ALTCOUNT,Number=1,Type=Integer,Description="Alternative Allele Count">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">

**Comment by pd3** [comment] 2020-03-05 13:36
This is caused by getopt_long() which reorders arguments passed to the plugins. An extra check would have to be added to catch this, not sure if it's worthwhile. Why do you need to use "-" when it works without it?

**Comment by ghuls** [comment] 2020-03-05 13:56
I had this code wrapped in a function:

```bash
add_AF_AC_AN () {
    local vcf_filename="${1}";

    bcftools plugin fill-tags "${vcf_filename}" -- -t 'AF,AC,AN'`

    return $?
}
```

In case you give "-" as argument, it wouldn't work.

**Comment by pd3** [comment] 2020-03-12 15:55
This should be fixed now. Please let me know if not.

**Closed** 2020-03-12 15:55 UTC
