### ISSUE TITLE
Indexing file error using tabix

### ISSUE THREAD

**Issue by sekhwal** [samtools/bcftools#1452] opened 2021-03-25 05:39 UTC
Hi,
I am trying to make a index of the vcf file using tabix. It shows following error. However, if I index file using "bcftools index", it make index file in .csi. Please help me to figure out the issue since I need to create index file using tabix (.tbi) to run a package.

I am using following command. 
bgzip file.vcf
tabix -p vcf file.vcf.gz

error:
[E::hts_idx_check_range] Region 537270101..537270102 cannot be stored in a tbi index. Try using a csi index with min_shift = 14, n_lvls >= 6
tbx_index_build failed: /bcftools-merged-all/index-merged/D.vcf2.gz

bcftools index file.vcf  ##It generate the index file in .csi

**Comment by valeriuo** [comment] 2021-03-25 06:23
The issue is TBI indices have an upper limit on the chromosome coordinates (2<sup>29</sup>-1), and your region is beyond that. CSI indices have extended this to 2<sup>31</sup>-1. BCFtools can also generate a TBI index by using the `-t` option, i.e. `bcftools index -t file.vcf.gz`, but you will likely get the same error.
The question is: what package are you trying to run that strictly requires a TBI index and cannot handle CSI?

**Comment by sekhwal** [comment] 2021-03-25 17:56
I am trying to use the following package. And the program won’t run without both a .vcf.gz and a .tbi. Could you please suggest if I can break the vcf file in several files using bcftools, each containing ~10-15 scaffolds? And then try creating the .vcf.gz and .tbi files for each group of scaffolds. Could you suggest any command for that.

https://cran.r-project.org/web/packages/PopGenome/vignettes/Whole_genome_analyses_using_VCF_files.pdf

**Comment by pd3** [comment] 2021-05-24 10:25
I've marked this as something that cannot be fixed on our end, large chromosomes must be indexed with csi.

**Closed by pd3** 2021-05-24 10:25 UTC
Labels: wontfix
