### ISSUE TITLE
call snps between groups

### ISSUE THREAD

**Issue by MariannaPd** [samtools/bcftools#363] opened 2015-12-17 16:38 UTC
Hi guys,
I'm dealing for the first time with the bcftools. I have not the most recent version.
I've called variants beteen two samples (control and treated) with these commands:
>samtools mpileup -uf ref.fa control.bam treated.bam | bcftools view -1 1 -bvcg - > var.raw.bcf 
>bcftools view var.raw.bcf | vcfutils.pl varFilter -D1000 > var.flt.vcf  

Now let's suppose we want compare two groups of samples (5 controls and 5 trated).
How can I do that?

Thank you in advance!!
Best
Marianna

**Comment by wkretzsch** [comment] 2015-12-20 17:23
Hi Marianna,
It's not quite clear what you mean by compare two groups of samples, so I'm going to just assume what you mean is this:

I have two VCF files with variants discovered in 5 controls (`controls.vcf.gz`) and 5 cases (`cases.vcf.gz`), respectively.  I want to know which variants were discovered in both groups, and which variants are private to each VCF.  The tool to use is `bcftools isec` to intersect VCFs.

This command creates both the intersect and complements of the VCFs and stores them in the directory `results`:
````
bcftools isec -p results controls.vcf.gz cases.vcf.gz
````

For more information about this sub-command see https://samtools.github.io/bcftools/bcftools.html#isec.

## Side note about versions

Bcftools does not have a stable branch, where I define "stable branch" as a bug fix only branch.  However, bugs are still common, although mostly in new features.  `bcftools isec` is an older feature, so you're probably fine with an older version of Bcftools.  However, if you're using newer features you may want to stay current with the `development` branch.

Winni

**Comment by pd3** [comment] 2015-12-20 20:11
This is a feature which was temporarily removed while transitioning to htslib, it was requested also by https://github.com/samtools/bcftools/issues/109. Sorry for not having done so yet. For now you could use PLINK, I was told its latest versions accept VCF files.

**Comment by jrandall** [comment] 2016-01-25 16:10
Closing this issue, as the `bcftools isec` functionality is in bcftools 1.3, and the basic association testing would be a duplicate of issue #109

**Closed by jrandall** 2016-01-25 16:10 UTC
