### ISSUE TITLE
bcftools reheader allow explicitely specifying output type

### ISSUE THREAD

**Issue by ghuls** [samtools/bcftools#1288] opened 2020-08-19 09:41 UTC
I run into a problem with `bcftools reheader`
As I am constructing the new header programmatically , the output file is corrupt if the input VCF file is gzipped or in BCF format (as I stream to stdout).
As the output would have a plain text header and a compressed VCF file or BCF file body.

Also is there a command like e.g. `bcftools info` that would give information about the VCF file compression format (e.g.: uncompressed VCF, compressed VCF, uncompressed BCF, compressed BCF)?

```
bcftools reheader -O "${vcf_input_file}"         -h <(
              # Create new VCF header:
              #   - Get VCF header of VCF input file.
              #   - Remove all contig header lines and "#CHROM" line from the VCF header.
              #   - Append contig headers in the order they appear in the input BAM file.
              #   - Add "#CHROM" line as last line of the new VCF header.
              bcftools view -h "${vcf_input_file}" \
                | awk \
                    '
                    {
                        if ($1 !~ /^##contig=/ && $1 !~ /^#CHROM/) {
                            # Remove all contig header lines and "#CHROM" line.
                            print $0;
                        }
                    }' \
                | cat \
                    - \
                    <(get_contig_order_from_bam "${bam_input_file}" 'vcf') \
                    <(bcftools view -h "${vcf_input_file}" | tail -n 1) \

            ) ${vcf_input_file} \
bcftools sort > output
```

**Comment by jmarshall** [comment] 2020-08-19 10:06
> bcftools reheader allow explicitely specifying output type

This part appears to be a duplicate of #1271.

> Also is there a command like e.g. bcftools info that would give information about the VCF file compression format

That's [**htsfile**](https://www.htslib.org/doc/htsfile.html).

**Comment by ghuls** [comment] 2020-08-19 10:20
@jmarshall Thanks for `htsfile` command.

I don't want conversion, but `bcftools reheader` seems to write a text header when the input file is given from stdin and that stream contains a compressed VCF or a BCF file. So it looks like it does not detect the format correctly to compress the header in the same format as the input file.

**Comment by jmarshall** [comment] 2020-08-19 10:47
I cannot reproduce any such problem, not even with the benefit of the vague description in the associated popscle_helper_tools issue.

If you think there's a bug here, please distill your _sort_vcf_same_as_bam.sh_ script down into a simpler complete self-contained `bcftools` invocation that demonstrates the problem.

**Comment by ghuls** [comment] 2020-08-19 12:36
I think I might have found a clue.

If I use `bcftools view -O z ${vcf_file_name}` to create a BGZP verion of the the gzipped VCF filename and use that as input, the code works.

With the gzipped VCF filename, `bcftools reheader` writes a corrupt gzipped file.

```
❯ zcat output_with_BGZP_as_input.vcf.gz | wc -l
3276589

❯ zcat output_with_gzipped_VCF_as_input.vcf.gz | wc -l

gzip: output_with_gzipped_VCF_as_input.vcf.gz: decompression OK, trailing garbage ignored
493
```

**Comment by jmarshall** [comment] 2020-08-19 12:44
Please show the complete `bcftools reheader` command that you think is writing a corrupt output file. What version of bcftools are you using?

**Comment by messwith** [comment] 2020-08-31 14:07
I have the same problem with bcftools 1.9
Input is vcf.gz file with genotypes simulated by pedsim
Compete command is:
`bcftools reheader data.vcf.gz -sample samplefile.samples -o test_data.vcf.gz`

File is corrupt after line 273 with the same decompression OK, trailing garbage ignored

**Comment by pd3** [comment] 2020-09-01 06:37
Probably a corrupt input file. Can you try `zcat data.vcf.gz >/dev/null`? If you believe the file is OK and it is a problem with bcftools, we'll need the file for testing.

**Comment by ghuls** [comment] 2020-09-01 07:50
Here is the problematic VCF file that I had: https://temp.aertslab.org/1000Genomes_hg38_CellRangerGenesOnly_Freemuxlet_0.1-0.9AF.vcf.gz

**Closed** 2020-09-03 08:12 UTC
Labels: needs-feedback

**Comment by pd3** [comment] 2020-09-03 08:21
There are several problems with your use of `reheader` which the program fails to report:
1. there is no option `-sample` so your command is interpreted as `-s ample`, however the failure was not checked
2. there are no FORMAT fields in your VCF, therefore it makes no sense to add samples
3. gzipped files are not supported by reheader, you'll need to convert to plain VCF, BCF, or BGZF-compressed VCF or BCF. This can be done using `bcftools view --output-type`.

All these issues are now addressed by the commits above.

**Comment by ghuls** [comment] 2020-09-03 14:34
@pd3 I assume only point 3 is valid for my file. Point 1 and 2 is for #1271, no? Thanks for fixing it.

**Comment by kelshmo** [comment] 2021-01-29 18:58
@pd3 If gzipped files are not supported by reheader, I suggest updating [the documentation](http://samtools.github.io/bcftools/bcftools.html#reheader) to not reference  _file.vcf.gz_.

**Comment by pd3** [comment] 2021-02-02 11:59
The suffix `.gz` is used for bgzipped compressed files, which is supported by `bcftools reheader`.
