### ISSUE TITLE
bcftools view silently ignores long lines

### ISSUE THREAD

**Issue by hannespetur** [samtools/bcftools#1614] opened 2021-11-17 11:18 UTC
Hello, thank you for your work on htslib and bcftools.

I am working with VCF files containing more than a hundred thousands of samples and I have noticed that "bcftools view" is silently ignoring any VCF records that are very long, I believe the problem starts occurring when the uncompressed line length exceeds 2^31 bytes (2GB). I have a script that can reproduce the problem by creating a dummy VCF file with a long line: https://gist.github.com/hannespetur/b8d44ba90deb3f4510753262a9db94ee

First argument is the number of samples the file has, second argument is the number of alternative alleles the record has. The VCF line has a PL value for each possible diploid genotype, so with more alternative alleles the line size grows very fast.

```sh
$ bash reproduce.sh 1000000 10 | bcftools view -H - | wc -l # 100,000 samples, 10 alts
1 # Expected
$ bash reproduce.sh 1000000 120 | bcftools view -H - | wc -l # 100,000 samples, 120 alts
0 # Not expected
```

I have noticed that bgzip can handle lines of this length
```sh
$ bash reproduce.sh 100000 120 | bgzip -c > test.vcf.gz
$ zgrep -v "^#" | wc -l
1 # Expected
```

however bcftools index/tabix cannot index the file.
```sh
$ bcftools index test.vcf.gz
index: failed to create index for "test.vcf.gz"
$ echo $?
255
```

Do you have any workarounds for working with large VCF lines like this?

### Tested on
Red Hat Enterprice Linux 7 (64-bit)
Intel Xeon E5-2690 v4
128 GB RAM
bcftools 1.14 and htslib 1.14. Problem was also reproduced on 1.10.2.

**Comment by pd3** [comment] 2021-11-18 13:09
This comes from a limitation of the BCF format which cannot represent lines longer than that. BCFtools / HTSlib use BCF as the internal format, even when on input is a VCF, it is first converted into BCF structures.

The big lines are usually caused by Number=G tags, such as genotype likelihoods (FORMAT/PL), therefore in practice we store their localized version as described here:
https://github.com/samtools/bcftools/blob/756e636433978daccd7daec12aec14fcf580eaf2/doc/bcftools.txt#L1744-L1753

If your large VCF is a product of `bcftools merge`, you can avoid the problem by adding the `-L` option to the command.

**Comment by hannespetur** [comment] 2021-11-18 15:51
Ok thank you for the explanation. I will try out using the FORMAT/LPL and FORMAT/LAA fields.

**Comment by pd3** [comment] 2021-12-16 11:54
I am closing it as this 1) cannot be fixed due to BCF spec limitation and 2) has a functional workaround

**Closed by pd3** 2021-12-16 11:54 UTC
Labels: htslib-dependent, cannot-fix
