### ISSUE TITLE
bcftools norm: Reference allele mismatch if there are special characters preceding or following the reference description

### ISSUE THREAD

**Issue by pdagosto** [samtools/bcftools#2021] opened 2023-10-16 17:27 UTC
bcftools version 1.8 (note this is a GMP validated application and we cannot easily change the version)
OS: CentOS 7

I am a software developer who works with bioinformaticians. I have been informed that they are having problems with bcftools norm if there are special characters preceding or following the description in the reference header, e.g..

>NC_001408.1 . Avian leukosis virus - RSA, complete genome- more text

This produces the following error:

Reference allele mismatch at NC_001408.1:1 .. REF_SEQ:'N' vs VCF:'G'

Some special characters produce the same type of error even if they appear inside the reference description, e.g.

>NC_001408.1 Avian leukosis virus - RSA, (complete genome) 

produces the following error:

Reference allele mismatch at NC_001408.1:1 .. REF_SEQ:'N' vs VCF:'G'

Some characters that appear inside the reference description without problems cause the same type of error if they precede or follow the description, i.e.:

>NC_001408.1 Avian leukosis virus - RSA, complete genome

is fine, but 

>NC_001408.1 Avian leukosis virus - RSA, complete genome ,

produces:

Reference allele mismatch at NC_001408.1:1 .. REF_SEQ:'N' vs VCF:'G'

Is it possible that this is a bug in the parsing of the reference header?

Please note that we are a contract testing organization and that receive these reference files from our clients. Since we are subject to GMP regulations we are not at liberty to edit the reference files.

**Comment by pd3** [comment] 2023-10-21 11:19
I don't think the problem is in the sequence header. If you look inside the VCF and the fasta file, the bases should match at the first position of the NC_001408.1 sequence. It seems the fasta starts with N whereas the VCF as G in the REF column at that position.

**Comment by pdagosto** [comment] 2023-10-24 14:14
The FASTA file does not start with N.

I've uploaded the FASTA file and the VCF file that bcftools norm used as input. I had to change the file extensions to .txt or the upload would not be accepted.

Here's the command line:
bcftools norm -O v -f NC_001408.fasta --threads 14 -o norm_call.vcf call_m.231013_aj04kv-x1_S1_M03133_1234.vcf

and here's the error message:
Reference allele mismatch at NC_001408.1:1 .. REF_SEQ:'N' vs VCF:'G'

[NC_001408.txt](https://github.com/samtools/bcftools/files/13116314/NC_001408.txt)
[call_m.231013_aj04kv-x1_S1_M03133_1234.txt](https://github.com/samtools/bcftools/files/13116317/call_m.231013_aj04kv-x1_S1_M03133_1234.txt)

Please note that the header:
>NC_001408.1 .(Avian leukosis virus - RSA, complete genome

is similar to one that we received from a client (with .( preceding the descirption). If the .( id removed bcftools completes normally.

**Comment by pd3** [comment] 2023-10-25 09:33
I am unable to reproduce the error regardles of the version bcftools I use
```
$ bcftools-1.8 --version
bcftools 1.8
Using htslib 1.8

$ bcftools-1.8 norm -O v -f NC_001408.fasta --threads 14 -o /dev/null call_m.231013_aj04kv-x1_S1_M03133_1234.vcf 
Lines   total/split/realigned/skipped:	7322/0/15/0

$ bcftools-1.18 --version
bcftools 1.18
Using htslib 1.18

$ bcftools-1.8 norm -O v -f NC_001408.fasta --threads 14 -o /dev/null call_m.231013_aj04kv-x1_S1_M03133_1234.vcf 
Lines   total/split/realigned/skipped:	7322/0/15/0
```

**Comment by pdagosto** [comment] 2023-10-25 13:46
Well I can reproduce it every single time I run it.

**Comment by pd3** [comment] 2023-10-31 13:26
What is the output of `bcftools --version`? What platform are you running this on? Does valgrind or other memory usage debugging techniques return anything suspicious?

**Comment by pdagosto** [comment] 2023-11-01 14:29
m240641@rckgxf0013 m240641]$ bcftools --version
bcftools 1.8
Using htslib 1.8
Copyright (C) 2016 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Haven't run valgrind or any other memory debugging tool.

**Comment by pd3** [comment] 2023-11-01 14:55
Can you show the output of
```
$ md5sum NC_001408.fasta
$ md5sum call_m.231013_aj04kv-x1_S1_M03133_1234.vcf
```

**Comment by pdagosto** [comment] 2023-11-01 16:34
$ md5sum NC_001408.fasta
e57c0464e4ea57bd8516cd7ade4c4fd8  NC_001408.fasta

$ md5sum norm_call_m.231013_aj04kv-x1_S1_M03133_1234.vcf
d41d8cd98f00b204e9800998ecf8427e  norm_call_m.231013_aj04kv-x1_S1_M03133_1234.vcf

**Comment by pdagosto** [comment] 2023-11-01 16:56
Correction for the md5sum for NC_001408.fasta. The one I sent previously did not have the special characters preceding the description$ md5sum NC_001408.fasta

36ff35fd627bb55133961b824c27ff2c  NC_001408.fasta

**Comment by pd3** [comment] 2023-11-02 13:05
These are not the files you made available in https://github.com/samtools/bcftools/issues/2021#issuecomment-1777307284. Those files give
```
54af99ac618f447d50f962af708798e0  call_m.231013_aj04kv-x1_S1_M03133_1234.vcf
2dff07255dc96824865b9184a0350938  NC_001408.fasta
```

**Comment by pdagosto** [comment] 2023-11-02 13:52
They may be from a different run of the same data. I have no idea why their MD5 sums are different. Ina nay case I have no more time to waste on this bullshit. I have already implemented a fix to eliminate the special characters form before and after the description.

**Comment by pd3** [comment] 2023-11-03 09:55
If the MD5 sums are different, it means also the content of the files is different. I suspect there is a problem at your end that you are unaware of; from what you showed it is highly unlikely the problem is in fasta sequence headers as you are suggesting.

I am closing this comment as the problem cannot be reproduced with the testing data provided, the report is inconsistent, and you inexplicably retreated to foul language despite my best efforts to help.

**Closed by pd3** 2023-11-03 09:55 UTC
Labels: requires-test-case
