### ISSUE TITLE
how to filter the roh based on the results by bcftools

### ISSUE THREAD

**Issue by yinhongwei4079** [samtools/bcftools#1568] opened 2021-08-26 13:57 UTC
Hi
 i had calculted the roh of individuals of our group but i didn't know how to filter the results. i know we can filter based on the Quality (average fwd-bwd phred score), could you give us a value of Quality (average fwd-bwd phred score) to filter?

                                                                        Best 
                                                                         Hongwei yin

**Comment by pd3** [comment] 2021-08-31 10:39
There is no one-size-fits-all threshold to apply I am afraid.

Just to cross reference the issues, this is a duplicate of #1529, specifically see https://github.com/samtools/bcftools/issues/1529#issuecomment-881535378.

**Closed by pd3** 2021-08-31 10:39 UTC
