### ISSUE TITLE
bcftools norm output truncated vcf files

### ISSUE THREAD

**Issue by yangyxt** [samtools/bcftools#1814] opened 2022-11-06 06:33 UTC
I tried bcftools norm to process a vcf file and found the output VCF is truncated in the middle, leaving the rest content compeletely lost. Here I paste the last few lines of the output:

![image](https://user-images.githubusercontent.com/40780228/200157554-306c0b72-07ca-43a9-ac09-579ecbd63faa.png)

Here is the command I used to get that output:
`bcftools norm -a --fasta-ref ucsc.hg19.fasta --check-ref s --multiallelics -both -Ov test_bcftools_norm.vcf.gz | less -S -`

Here I provide the vcf file for testing. Btw, the version of bcftools I used is 1.15.
[test_bcftools_norm.vcf.gz](https://github.com/samtools/bcftools/files/9945257/test_bcftools_norm.vcf.gz)

**Comment by yangyxt** [comment] 2022-11-06 06:53
btw, I just tested the 1.16 version. The issue is still there.

**Comment by yangyxt** [comment] 2022-11-06 07:03
Also, I think this is relevant with --multiallelics -both parameter. Because when I remove the argument --multiallelics, the issue goes away. But I need the spliting multiallelic feature.

**Comment by pd3** [comment] 2022-11-07 09:38
Thanks for the test case.

The output is truncated because of premature termination of the program, you most likely missed this error message
```
Error at 11:67763052, the tag PL has wrong number of fields
```
This site has the following alleles
```
11  67763052    .   C   *,A,G
```
but only three PL values 5561,588,0. The tag is defined as Number=G, therefore 10 values are expected.

You can either fix this upstream, or reheader the PL tag as Number=., or remove the tag completely if you don't need it.

As such I am closing the issue because this is the expected behavior.

**Closed by pd3** 2022-11-07 09:38 UTC
