### ISSUE TITLE
Subset of samples doesn't work if the header doesn't include contig tag 

### ISSUE THREAD

**Issue by mfoll** [samtools/bcftools#326] opened 2015-09-24 15:31 UTC
Hi,

On this simple VCF `test.vcf`:

```
##fileformat=VCFv4.1
##INFO=<ID=TEST1,Number=1,Type=Integer,Description="Test1">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=TEST2,Number=1,Type=Integer,Description="Test3">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  sample1 sample2
chr1    1   .   A   T   100 .   TEST1=10    GT:TEST2    0/1:10  0/1:30
chr1    2   .   A   T   100 .   TEST1=50    GT:TEST2    0/1:20  0/1:40
```

This command:

``` bash
bcftools view -s sample1 test.vcf
```

Leads to:

```
[W::vcf_parse] contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
Undefined tags in the header, cannot proceed in the sample subset mode.
```

Simply adding:

```
##contig=<ID=chr1,length=135006516>
```

in the header and it runs. 

On page 3 of [VCF specs](http://samtools.github.io/hts-specs/VCFv4.1.pdf) one can read that the contig tag is optional:

> 1.2.7 Contig field format
> As with chromosomal sequences it is highly recommended (but not required) that the header include tags describing the contigs referred to in the VCF file.

**Comment by wkretzsch** [comment] 2015-09-24 17:01
For this functionality to work, bcftools apparently needs the contig to be specified in the header.  What's wrong with that?

**Comment by mfoll** [comment] 2015-09-24 17:21
Nothing wrong, but rather an unexpected behaviour as:
- The contig tag is optional in VCFs
- Other bcftools filter commands don't need it
- I don't see any reason why subsetting on samples would particularly need it

**Comment by wkretzsch** [comment] 2015-09-24 17:46
I agree with the sentiment.  It might be helpful to have some guidance in the documentation on when and when not bcftools needs the contig tag.

As for expected behavior, here is my intuition as to why `bcftools filter` works quite differently from `bcftools view -s`:

Subsetting samples and filtering out sites are two different operations.  One cuts down columns, while the other drops lines of the file.  As you probably know from using command line tools like perl or awk, dropping a line is as simple as identifying a line to drop and then just not printing it.  Cutting down columns on the other hand usually requires a more detailed parsing of the line.  

My guess is that the line writer in bcftools needs the contig tag to be defined in order to rewrite the lines correctly.

**Comment by mfoll** [comment] 2015-09-24 18:01
Actually by "other bcftools filter commands" I was thinking of `bcftools view` (I forgot there is also a `filter` command, sorry for the confusing wording...), like `bcftools view -i` for example. But you are right, it seems linked to deleting columns.

**Comment by kevinrue** [comment] 2015-10-08 10:33
Dear all,

I ran into a similar issue, using the "bcftools query" command.
in my case the header does include the contig lines, e.g.:
```
 ##contig=<ID=1,length=249250621>
```

The command I ran was 
```
bcftools query\
  -r $chrom:$chromStart-$chromEnd\
  -s sample1,sample2,sample3\
  -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/AC\t%INFO/AN\n'\
  -o table.txt\
  file.vcf.gz
```

(Note: I give here a fake list of sample names for clarity, I had several hundreds of them)

(Note 2: I can guarantee that all sample names are present in the VCF file as the equivalent "bcftools view" command worked fine with the same sample list)

Can anyone else replicate this issue of sample subsetting using the "bcftools query" command, or did I do something wrong here?

Many thanks!

**Comment by pd3** [comment] 2015-10-08 10:49
Hi, the `query` command just issues a warning which you can safely ignore.  But I see this needs a bit of explanation:

VCF is internally represented as BCF file format which encodes tags by their implicit order in the header and throughout the file refers to these IDs. When parsing a VCF with undefined tags, the IDs are created on the fly. This approach fails when the output file is BCF as the header has been already printed. 

In some situation this does not matter (as in the `query` command), but you still get a warning from htslib. In other situations it shouldn't matter but the commands complain and exit anyway: these could be improved so that they detects if the undefined tags are harmful or not. 

A quick workaround is to include all tags using `bcftools reheader` or `bcftools annotate -h`.

**Comment by wkretzsch** [comment] 2015-10-08 10:52
@kevinrue : I can't replicate your issue without knowing what is in your `file.vcf.gz`.  Can you post a minimal example vcf if this is still an issue?

**Comment by pd3** [comment] 2015-10-08 10:55
@wkretzsch This affects any VCF with a contig line removed. For example, `bcftools query -f'%POS\n'`, will produce the following warning:

     [W::vcf_parse] contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)

**Comment by kevinrue** [comment] 2015-10-08 11:44
@pd3
I don't get any warning.

@wkretzsch 
The VCF.gz file I am working on is sensitive (human data). It is the only one I have at the moment, so I don't have any VCF file to share, I am sorry.

If describing "what is in my file.vcf.gz" can help you, it is a merged VCF file of several thousands of samples, and all variants on all chromosomes. The header include INFO, FORMAT and contig information.

Is that enough for you to work with? I am sorry I can't share any part of this file. I was hoping that this issue would be by others using a vcf.gz file of their own; specifying a subset of sample names from your own file using the -s flag (e.g., sample1,sample2,sample3) should replicate the issue if there is any, otherwise it would mean something is wrong on my side.

Thanks again for the quick answers, and apologies for my delay in replying. Trying to figure it out myself at the same time!

**Comment by wkretzsch** [comment] 2015-10-08 13:09
@kevinrue 
No, sorry, that's not enough to work with.  I will need a minimal, complete, and verifiable example as defined [here](https://stackoverflow.com/help/mcve).  I don't recommend sharing your sensitive VCF.  Instead make up a minimal VCF that still reproduces the error you are seeing.  Chances are that while making up the VCF you will figure out what is causing your error.  If that happens, please do post back as well.   

By the way, a good example of how to post such a minimal example is the first post in this thread.

**Comment by kevinrue** [comment] 2015-10-08 14:45
Alright, adapting the minimal example in the first post.

```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1,length=135006516>
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=TEST2,Number=1,Type=Integer,Description="Test3">
##bcftools_viewVersion=1.2+htslib-1.2
##bcftools_viewCommand=view test.vcf
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1 sample2
chr1    1       .       A       T       100     .       AN=4;AC=2       GT:TEST2        0/1:10  0/1:30
chr1    2       .       A       T       100     .       AN=4;AC=1       GT:TEST2        0/0:20  0/1:40
```

I highlight the features important for my use-case:
- 2-sample VCF file
- AC (allele count) and AN (allele number) in the INFO field
- In both cases, 4 calls (AN=4)
- In one case, ALT is seen twice (AC=2), the other once (AC=1)

Now, when I run:
```
bcftools view -s sample1 test.vcf
```
As I expect, I see the AN and AC being updated (sample1 has only 2 calls, with ALT alleles 1 and 2 present once and absent respectively):
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1
chr1    1       .       A       T       100     .       AN=2;AC=1       GT:TEST2        0/1:10
chr1    2       .       A       T       100     .       AN=2;AC=0       GT:TEST2        0/0:20
```

However, when I perform the same operation using `bcftools query`
```
bcftools query -s sample1 -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/AC\t%INFO/AN\n' test.vcf
```
the sample subsetting does not seem to work (again, I repeat: no warning message). The AC and AN (last two columns, in that order) match the information corresponding to the full original file, instead of the desired subset
```
chr1    1       A       T       2       4
chr1    2       A       T       1       4
```

Thanks in advance for you help @wkretzsch  !

**Comment by mfoll** [comment] 2015-10-08 14:50
I doesn't seem related to the original issue to me. I think you should open another issue for this one.

**Comment by kevinrue** [comment] 2015-10-08 14:52
true, the "Subset of samples doesn't work" is the same result, but obviously the cause is different.
Apologies,I will post the same thing in a new issue.
Thanks

**Comment by wkretzsch** [comment] 2015-10-09 10:45
OK, just for book keeping the @kevinrue reposted this question as issue #331

**Comment by pd3** [comment] 2018-01-03 15:58
I believe this was resolved. If not, please open an issue, this thread is long and confusing.

**Closed by pd3** 2018-01-03 15:58 UTC

**Comment by Syeda12** [comment] 2019-09-21 10:49
dear all
i have same issue..
this is the sample file: HG02494
HGDP00094
HGDP00099
HGDP00102
HGDP00056
HGDP00068
HGDP00070
HGDP00037
HGDP00049
HGDP00001
HGDP00013
HGDP00082
HGDP00119 etc...
and have chr11 vcf file
use a command (bcftools view --sample-file sample.txt chr11.vcf)
and its lead to this error...
[subset called for sample that does not exist in header: HGDP 00094.]
please require some help on this...

**Comment by winni2k** [comment] 2019-09-23 08:11
@Syeda12, welcome! This issue has gotten long and confusing. Can you please open a new issue for your problem?

**Comment by pd3** [comment] 2019-09-25 13:03
Most likely there is a typo in your sample file, the error message suggests there is a space in the sample name.
