### ISSUE TITLE
Wrong IDV/IMF values

### ISSUE THREAD

**Issue by finswimmer** [samtools/bcftools#911] opened 2018-11-02 09:10 UTC
Hello,

I'm using bcftools v1.9 and doing variant calling like this:

```
bcftools mpileup -Ou -C 70 -E -q 20 -f ref.fa -R regions.bed -a FORMAT/DP input.bam \
| bcftools call -m -v \
| bcftools norm -f ref -o output.vcf
```

If I take a look at indel I can see this:

```
1       16046704        .  CCTT    C       222     PASS    INDEL;IDV=30;IMF=0.47619;DP=63;VDB=0.789594;SGB=-0.693079;MQSB=0.989158;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=11,23,9,20;MQ=59;SSR=0,0     GT:PL:DP        0/1:255,0,255:63
1       47225894        .     GGGCA   G       228     PASS    INDEL;IDV=1;IMF=0.00819672;DP=122;VDB=1.72197e-07;SGB=-0.693147;MQSB=0.967787;MQ0F=0;AC=2;AN=2;DP4=3,7,46,66;MQ=59;SSR=0        GT:PL:DP        1/1:255,120,0:122
```

The first variant looks fine to me, as I would expect that the IDV value is at least as high as the sum of the DP4 values for ALT.

But the second variant has an IDV value of 1, which doesn't make sense to me.

What's going on here?

fin swimmer

**Comment by finswimmer** [comment] 2018-11-02 09:45
This seems to happen if there is another indel next to it. For the variant above this looks like this in igv:

![IGV][1]

I checked this behaviour for multiple indels, with all the same result. The IDV value seems to be correct, instead the DP4 values are missleading/wrong?

fin swimmer

[1]: https://imgdb.net/images/4301.png

**Comment by pd3** [comment] 2018-11-04 20:38
This would need some test data and more time to make sure, but my guess is that the realignment is might be causing these discrepancies.

**Comment by pd3** [comment] 2018-11-17 16:05
This is a duplicate of https://github.com/samtools/bcftools/issues/912. I am closing this issue as it is referenced from there already.

**Closed by pd3** 2018-11-17 16:05 UTC
