### ISSUE TITLE
Error: Invalid format for pileup at line 1

### ISSUE THREAD

**Issue by nengcheng** [samtools/bcftools#878] opened 2018-09-07 07:24 UTC
I use bcftools to generate mplileup file as samtools are deprecated recently.  It worked after remove the firtstline of pileup file. But the pilefile is super huge 100G plus, it's quit time-consuming to remove the headlline.  the "#" symbol should added to the first line, which looks like <BCF**filemormat=VCFv.4.2>

the problem is that when I removed the first line. the mpileup file format changed from octet-stream to text format, and it cause problems (repeat message: input stream not ready, waiting for 5 seconds ) using varscan to call the SNP.

**Comment by tseemann** [comment] 2018-09-08 09:05
I think `varscan` still needs the old style `samtools mpileup`, it's still available in samtools 1.9

**Comment by nengcheng** [comment] 2018-11-20 07:11
It seems that bcftools and samtools are generating two totally different pileup formats! ( I don't know why they suggest using bcftools).  I just use the newest version for all tools.  So, if I need to use varscan, I have to use samtools to generate mpileup file ( they are compatible ). and for bcftools calling, I need to use bcftools for generating the pileup file.

**Comment by pd3** [comment] 2018-11-20 07:59
That's correct. I believe the issue is resolved by this, I'll close the issue now.

**Closed by pd3** 2018-11-20 07:59 UTC
Labels: needs-feedback

**Comment by nengcheng** [comment] 2018-11-26 04:10
>           That's correct. I believe the issue is resolved by this, I'll close the issue now.

Yes, it's solved. Thank you .
