### ISSUE TITLE
Warning: fewer CSQ fields than expected

### ISSUE THREAD

**Issue by kuaileshizuihao** [samtools/bcftools#2295] opened 2024-09-28 14:04 UTC
After merging files from different samples using "bcftools merge", I encountered a problem while using bcftools +split-vep, which resulted in this error. I filtered out the lines causing the error and saved them as Error.vcf. Initially, I suspected that the “|” symbol in the GT field might be interfering with the recognition of the fields, so I replaced all GT information with “.” However, the error still persists. This has been a source of frustration for me for two weeks. Thank you very much for your assistance!

```
bcftools +split-vep "/ehpcdata/analysis/chenhaijie/Compare/Error.vcf" -H -d -A tab -f '%ID\t%CHROM\t%REF\t%ALT\t%CSQ' -s all:missense+ -o /ehpcdata/analysis/chenhaijie/Compare/ErrorSplited.vcf
# Warning: fewer CSQ fields than expected at chr1:201359246, filling with dots. This warning is printed only once.
```
[Error.vcf.zip](https://github.com/user-attachments/files/17174616/Error.vcf.zip)

**Comment by pd3** [comment] 2024-10-10 11:38
As the warning error message suggests, this is solely about the INFO/CSQ field and is not relevant to GT.

In the VCF header the CSQ field has 78 subfields (separated with `|`), but the majority of the data lines, 148 to be exact, there have only 53
```
# this extracts the CSQ tags, splits by comma, then prints the number of subfields
$ bcftools query -f'%CSQ' Error.vcf | sed 's/,/\n/g' | awk -F\| '{print NF}' | sort | uniq -c
    148 53
     47 78
``` 

But since you say the file is a result of a `bcftools merge` operation: is it possible that the CSQ fields were generated prior to merging and each file had different CSQ lines?

In any case, the program works as expected, therefore I'll close the issue - the problem is with the input data, not with the program.

**Closed by pd3** 2024-10-10 11:38 UTC
