### ISSUE TITLE
vcf-plot error 

### ISSUE THREAD

**Issue by aderzelle** [samtools/bcftools#618] opened 2017-05-23 16:59 UTC
Hello, 

I am using the last developmental version of bcftools and htslib. Attempting to plot with vcf-tools returns the following error code:

```
File "plot.py", line 80, in <module>
    for row in reader:
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
The command exited with non-zero status 256:
	python plot.py

 at /usr/local/bin/plot-vcfstats line 76.
	main::error("The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}") called at /usr/local/bin/plot-vcfstats line 276
	main::plot(HASH(0x19354a0)) called at /usr/local/bin/plot-vcfstats line 65

```

For the record, I am on Manjaro Linux, default Python is Python 3 (not 2). 
Thanks for your help

**Comment by pd3** [comment] 2017-05-24 11:31
Any chance you could send me the output from `bcftools stats` for me to take a look?

**Comment by aderzelle** [comment] 2017-05-24 14:03
Sure no problem, where shall I send it?

**Comment by pd3** [comment] 2017-05-24 14:15
There is an email on my profile page, thanks

**Comment by pd3** [comment] 2017-05-26 10:24
Thanks for the data, the problem should be fixed by this commit

**Closed** 2017-05-26 10:24 UTC

**Comment by freeseek** [comment] 2018-02-06 22:38
@pd3 I had the same issue while using "bcftools cnv". The problem is in vcfcnv.c and is quite easy to fix. You have multiple instances of code that looks like this:
```
            "   with open(file, 'rb') as f:\n"
            "       reader = csv.reader(f, 'tab')\n"
```
The problem here is that python3 csv module does not like files to be opened in binary mode and it throws the following error:
```
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```
The fix, I am guessing, is to replace all the instances of `open(file, 'rb')` with `open(file, 'r')`.
