### ISSUE TITLE
segfault +setGT -i'INFO/DP'

### ISSUE THREAD

**Issue by sahwa** [samtools/bcftools#982] opened 2019-03-15 19:20 UTC
I'm trying to set positions with total depth of less than 2 as missing using setGT:

`bcftools +setGT -O v -o test.out in.vcf.gz -- -n . -t q -i'INFO/DP<2'`

`Segmentation fault`

Whereas

`bcftools +setGT -O v -o test.out in.vcf.gz -- -n . -t q -i'FORMAT/DP<2'`

`Filled 132 alleles`

header lines:

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##source=ATLAS
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods">
##FORMAT=<ID=GG,Number=10,Type=Integer,Description="Phred-scaled likelihoods for all genotypes in alphabetical order">
##contig=<ID=1>
##contig=<ID=2>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##bcftools_viewVersion=1.9+htslib-1.9

```

Info lines:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Molz1
1	752566	.	G	A	.	.	DP=16;AC=2;AN=2	GT:AD:DP:GQ:PL:GG	1/1:0,16:16:48:472,48,0:0,48,48,48,616,511,616,472,511,616
```

if I run:

`bcftools view -i'INFO/DP<2' in.vcf.gz > test.out`

I get the correct output, suggesting there is something up with the plugin?

**Comment by pd3** [comment] 2019-03-20 15:56
Hi, I am unable to reproduce the error. Are you running bcftools version 1.9 as your header suggests? Can you try with the latest development version from github? If nothing works, can you provide a small test case to reproduce the problem?

**Comment by pd3** [comment] 2019-03-22 15:57
Thank you for the test case. This is now fixed.

**Closed** 2019-03-22 15:57 UTC
Labels: needs-feedback
