### ISSUE TITLE
bcftools - issue when trying to merge two VCFs

### ISSUE THREAD

**Issue by AshleyShi2000** [samtools/bcftools#1685] opened 2022-03-22 22:59 UTC
I'm getting this error when trying to merge my two VCF files. I first used bgzip to compress my files and then indexed them before merging.  
**Not ready for type [0]: SNP at 82113**

Thanks for helping!

**Comment by pd3** [comment] 2022-03-25 10:45
That's indeed a very cryptic message, did not expect to ever encounter such case. Could you please check the headers and show which the tags are defined as Number=G/A/R? A small test case to reproduce the problem would be really helpful here.

**Comment by AshleyShi2000** [comment] 2022-03-28 22:22
I've uploaded the original files to OneDrive! 
[https://1drv.ms/u/s!AuZRdpWMK4MxgUVCAKTE_X6r9Y5a?e=JJ3vfe](url)

These are the commands that I used:
bgzip -c DTB-003.vcf > DTB003.vcf.gz
bcftools index DTB003.vcf.gz 
bgzip -c DTB-005.vcf > DTB005.vcf.gz
bcftools index DTB005.vcf.gz    
bcftools merge DTB003.vcf.gz DTB005.vcf.gz > merged.vcf
Not ready for type [0]: SNP at 82113

The tags that are defined as Number=A are:
##INFO=<ID=VARTYPE,Number=A,Type=String,Description="Comma separated list of variant types. One per allele">
##INFO=<ID=SNP,Number=A,Type=Flag,Description="Variant is a SNP">
##INFO=<ID=MNP,Number=A,Type=Flag,Description="Variant is a MNP">
##INFO=<ID=INS,Number=A,Type=Flag,Description="Variant is a INS">
##INFO=<ID=DEL,Number=A,Type=Flag,Description="Variant is a DEL">
##INFO=<ID=MIXED,Number=A,Type=Flag,Description="Variant is a MIXED">
##INFO=<ID=HOM,Number=A,Type=Flag,Description="Variant is homozygous">
##INFO=<ID=HET,Number=A,Type=Flag,Description="Variant is heterozygous">

I hope these are what you're looking for. Thanks again for your kind help!

**Comment by pd3** [comment] 2022-03-29 08:35
Thank you for the test files. The problem is caused by flag types being defined as `Number=A`. This violates the VCF specification which explicitly states that
```
The ‘Flag’ type indicates that the INFO field does not contain a Value entry, and hence the Number must be 0
in this case.
```

An easy workaround should be to fix the header
```
bcftools view -h file.bcf > hdr.txt
# edit the header and change all Type=Flag tags to Number=0
bcftools reheader -h hdr.txt file.bcf -o fixed.bcf
```

Ideally the program that produced the VCFs should be fixed.

**Comment by pd3** [comment] 2022-04-01 14:35
This is now merged via https://github.com/samtools/htslib/pull/1415

**Closed by pd3** 2022-04-01 14:35 UTC
Labels: htslib-dependent
