### ISSUE TITLE
bcftools merge --file-list dies if the list is too long

### ISSUE THREAD

**Issue by iqbal-lab** [samtools/bcftools#329] opened 2015-10-03 00:13 UTC
If I give it a list of 2600 files (all with identical first 9 columns, just different final column, one sample per VCF), it fails at line 1021, with

bcftools merge --file-list listvcfs -o foobar
Failed to open whatever.vcf.gz: could not load index

**Comment by mcshane** [comment] 2015-10-03 06:47
For merge, all the input VCFs must be bgzipped and indexed. Do all the index files exist?

**Comment by jaredo** [comment] 2015-10-03 08:58
If the index files do exist, you might be running into the limit for number of open files. This happens to me quite a lot! You can check/set it with `ulimit -n`

**Comment by mcshane** [comment] 2015-10-03 13:35
I'm guessing Jared is right about your issue. Let me know if not.

**Comment by iqbal-lab** [comment] 2015-10-04 14:53
Pretty sure indexes all there. Will check. File handles a good thought. Will check

**Comment by mcshane** [comment] 2015-11-09 14:24
Hi Zam. Did you track down whether this was a ulimit issue? If so will close and @adamspargo will open a new issue about reporting back ERRNO to the user.

**Comment by jrandall** [comment] 2016-01-25 11:48
@iqbal-lab, it seems very likely that this turned out to be an issue with limits, so if we don't hear from you we'll assume that using `ulimit -n` was able to address it for you. Meanwhile I have opened a new issue  (#376) suggesting a usability fix for this issue.

**Closed** 2016-01-25 16:07 UTC

**Comment by iqbal-lab** [comment] 2016-01-25 17:45
Sorry, I'll chase down how I fixed it. Was not with ulimit.

**Comment by Shicheng-Guo** [comment] 2020-03-06 05:17
I met the same problem. bcftools merge will report an error and will stop if file lists > 1021

```
[E::hts_idx_load3] Could not load local index file '229209.fstl1.vcf.gz.tbi'
Failed to open 229209.fstl1.vcf.gz: could not load index
```

**Comment by Sanyukta2001** [comment] 2024-02-14 13:05
@Shicheng-Guo Hi, How did you solve this issue? I am facing the same problem. My ulimit is higher than my number of vcf files so I don't know what the issue is.

**Comment by ckandoth** [comment] 2026-02-19 11:41
@Sanyukta2002 You'll need twice as many as the VCF files. One per VCF and one per VCF index. And maybe one more file handle that writes the output VCF. There's no (immediate) harm in setting it to something way higher than you might ever need like `ulimit -n 65535`.
