### ISSUE TITLE
bcftools csq abort trap runtime error

### ISSUE THREAD

**Issue by chmille4** [samtools/bcftools#1429] opened 2021-02-23 15:45 UTC
### Description
I'm hitting this repeatable runtime error when running bcftools csq (version 1.11) on OSX. The error and files needed to recreate are below.

### Error:
```
$ bcftools csq -p a -n 3   -f references_hs37d5_hs37d5.fa.gz -g Homo_sapiens.GRCh37.87.gff3.gz   https://frameshiftpublictest.s3.amazonaws.com/platinum-exome.vcf.gz > out.vcf
Parsing Homo_sapiens.GRCh37.87.gff3.gz ...
Indexed 196476 transcripts, 1195710 exons, 724218 CDSs, 280277 UTRs
Ignored the following biotypes:
	46x	.. 3prime_overlapping_ncrna
Calling...
Warning: Too many consequences for sample NA12877 at 1:909238, keeping the first 3 and skipping the rest.
         The limit can be increased by setting the --ncsq parameter. This warning is printed only once.
Warning: Skipping overlapping variants at 4:1388379, sample NA12877	G>A.
         This message is printed only once, the verbosity can be increased with `--verbose 2`
bcftools(92287,0x10bcefdc0) malloc: *** error for object 0x7f8042e4dfff: pointer being freed was not allocated
bcftools(92287,0x10bcefdc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

### Files to recreate
1. Reference - https://storage.cloud.google.com/genomics-public-data/references/hs37d5/hs37d5.fa.gz (have to gunzip and bgzip first)
2. VCF File - https://frameshiftpublictest.s3.amazonaws.com/platinum-exome.vcf.gz
3. GFF3 File - ftp://ftp.ensembl.org/pub/grch37/release-87/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz

**Comment by pd3** [comment] 2021-02-24 16:12
I was unable to reproduce the problem. What version of bcftools are you running?

**Comment by chmille4** [comment] 2021-02-24 17:39
This looks to be an OSX specific issue. If I run the above on Linux it works no problem. I'm using bcftools v1.11

**Comment by jmarshall** [comment] 2021-02-24 22:10
You don't get the same crash on Linux, but valgrind does detect the problem when run with these data files — starting with (with current **develop**):

```==198776== Invalid read of size 4
==198776==    at 0x517731: bcf_enc_vint (in /home/…/bcftools/bcftools)
==198776==    by 0x520EE6: bcf_update_format (in /home/…/bcftools/bcftools)
==198776==    by 0x4A53C2: vbuf_flush (csq.c:3249)
==198776==    by 0x4AAAC7: process (csq.c:4042)
==198776==    by 0x4AAAC7: main_csq (csq.c:4221)
==198776==    by 0x63C3872: (below main) (in /usr/lib64/libc-2.28.so)
==198776==  Address 0x1daeef60 is 0 bytes after a block of size 16 alloc'd
==198776==    at 0x4C331EA: calloc (vg_replace_malloc.c:762)
==198776==    by 0x4A5103: vbuf_push (csq.c:3187)
==198776==    by 0x4AAA4E: process (csq.c:4027)
==198776==    by 0x4AAA4E: main_csq (csq.c:4221)
==198776==    by 0x63C3872: (below main) (in /usr/lib64/libc-2.28.so)
```

**Comment by pd3** [comment] 2021-02-25 13:22
Thank you both. I just pushed a fix, can you please try it out?

**Closed** 2021-02-25 13:22 UTC

**Comment by chmille4** [comment] 2021-02-25 14:57
Hi Petr, I just tested on OSX and it worked. Thanks very much for the quick fix!
