### ISSUE TITLE
bcftools loss record in targets when it comes with a G after pos.

### ISSUE THREAD

**Issue by sssimonyang** [samtools/bcftools#1598] opened 2021-10-18 12:08 UTC
```
$ bcftools --version
bcftools 1.13
Using htslib 1.13
```
I have a sites.txt and a temp.vcf.

```
$ cat site.txt
1       10001   G       A
1       10002   A       A
1       10003   G       C
1       10004   A       C
$ cat temp.vcf
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=20000000>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       10001   .       G       C       40      .       .
1       10002   .       T       A       50      .       .
1       10003   .       A       G       60      .       .
1       10004   .       A       T       70      .       .
```

Use bcftools view to get site in sites.txt.

```
$ bcftools view -T site.txt temp.vcf
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=20000000>
##bcftools_viewVersion=1.13+htslib-1.13
##bcftools_viewCommand=view -T site.txt temp.vcf; Date=Mon Oct 18 20:03:23 2021
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       10002   .       T       A       50      .       .
1       10004   .       A       T       70      .       .
```
The third columns of 10001 and 10003 is both G.

Only using the first two columns will help.

```
$ awk '{print $1"\t"$2}' site.txt > site1.txt
$ bcftools view -T site1.txt temp.vcf
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=20000000>
##bcftools_viewVersion=1.13+htslib-1.13
##bcftools_viewCommand=view -T site1.txt temp.vcf; Date=Mon Oct 18 20:04:41 2021
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       10001   .       G       C       40      .       .
1       10002   .       T       A       50      .       .
1       10003   .       A       G       60      .       .
1       10004   .       A       T       70      .       .
```

But it is unexpected that the unused columns have effect on result.

**Comment by sssimonyang** [comment] 2021-10-19 12:02
Please note that in above example, the 10002 and 10004 being queried out is not for their REF ALT being matched.
In site.txt, the record is 10004 A C and in vcf, it is 10004 A T.

So I think it is not due to matching REF and ALT.

**Comment by pd3** [comment] 2022-02-11 15:54
Thank you both for the report, apologies for taking so long to look at it. For now just want to acknowledge that the problem is indeed real and the cause has been traced and found to code in htslib.

**Comment by pd3** [comment] 2022-02-14 10:46
This issue should resolve once https://github.com/samtools/htslib/pull/1396 is merged.

**Comment by pd3** [comment] 2022-02-18 08:50
This should be now resolved.

**Closed by pd3** 2022-02-18 08:50 UTC
Labels: bug, documentation

**Comment by SunWinner01** [comment] 2024-11-18 13:26
Hello, sorry to bother you. Currently, I’m using the command `bcftools view -m 2 -M 2 --threads 4 -Ob -o referencePanel.22.bcf referencePanel.vcf.gz` to process my data. My file `referencePanel.vcf.gz` contains a combination of SNPs and structural variant (SV) data, with SV information included among the SNPs. However, after running this command, I noticed that there was no change in the resulting file. I’d like to ask if this is normal, as I have the following questions:

1. Does `bcftools view -m 2 -M 2` have no effect on SV data?
2. What kind of SNPs would not pass the filter using the command `bcftools view -m 2 -M 2`?
3. In my file, the REF and ALT columns of the SNP data are composed solely of one of the letters A, G, C, or T.

These are all my questions. I look forward to your reply! Thank you so much, and I wish you all the best. @sssimonyang @tobyaicher
